### ISSUE TITLE
[Feat] Could the Data be appended to the End of file?

### ISSUE THREAD

**Issue by Quorafind** [Vinzent03/obsidian-advanced-uri#1]
# WHAT

I found that the append mode allows us to append data to the begining of the file. But I think append means that add things to the end, and prepend means that add things to the beginning.

# HOW

I think it would be nice that add an action name: prepend and append. That are both useful for people. 

Thanks for building such a good job.

**Comment by Vinzent03** [comment]
Oh you are right. That was a mistake. Will fix it today. Thanks for reporting.
