### ISSUE TITLE
Add toggle command to enable and disable commands for plugins

### ISSUE THREAD

**Issue by Archie-2021** [Vinzent03/obsidian-advanced-uri#103]
I think using a single command to toggle a plugin instead of enabling and disabling it separating makes more sense. Less hotkeys required for that.

Also I just found out about this awesome feature in your plugin, but I am not sure how to use it as documentation on it is thin and doesn't include an example (my memory of how this plugin works also a bit rusty as it has been a while since last I used it, so I apologize in advance). Can you help me with an example format on how it works, I want to use it on a plugin installed via BRAT. Is that going to make a difference?

Thank you

**Comment by Vinzent03** [comment]
As documented [here](https://vinzent03.github.io/obsidian-advanced-uri/actions/miscellaneous) the parameter is `enable-plugin` or `disable-plugin`. The rest tho is not good documented you are right. The value is the plugin's id. You can get it on GitHub in the [manifest.json](https://github.com/Vinzent03/obsidian-advanced-uri/blob/master/manifest.json) file. For this plugin it's `obsidian-advanced-uri`. I don't plan on adding another parameter to enable and disable it tho.

Full example: `obsidian://advanced-uri?vault=<vault>&enable-plugin=obsidian-advanced-uri`

**Comment by Archie-2021** [comment]
> 

Thank you very much , it works like a charm now. I hope you change your mind on the toggle later.

**Comment by Vinzent03** [comment]
I'm closing this as I don't plan on implementing this.
