### ISSUE TITLE
Is it possible to daisy chain commands together?

### ISSUE THREAD

**Issue by danrfletcher** [Vinzent03/obsidian-advanced-uri#105]
Hello, 

Firstly thanks for this excellent plugin. I was looking to daisy chain some commands together to open my daily note, append a template & execute the templater command to replace templates in the active file. I have read the documentation & became much more familiar with the advanced URI syntax but so far have been unable to get this working using the following:

obsidian://advanced-uri?vault=Vault&daily=true&commandid=obsidian-hotkeys-for-templates%253AEvening%2520Journal%2520Template.md&mode=append&commandid=templater-obsidian%253Areplace-in-file-templater

obsidian://advanced-uri?vault=Vault&daily=true&commandid=obsidian-hotkeys-for-templates%253AEvening%2520Journal%2520Template.md&commandid=templater-obsidian%253Areplace-in-file-templater
&mode=append

I'm wondering if this is currently possible?

Many Thanks

**Comment by Vinzent03** [comment]
You can only call one command per URI. So you have to call multiple URIs one by one.

**Comment by danrfletcher** [comment]
Ok thanks for the clarification.

**Comment by danrfletcher** [comment]
Not currently possible

**Comment by FelipeRearden** [comment]
> Ok thanks for the clarification.

You can combine this amazing plugin with two other plugins to achieve want you want:

1 [URI Commands](https://github.com/kzhovn/uri-commands-obsidian) to run URI as a command 

2 [Quick Add](https://github.com/chhoumann/quickadd) to daisy chain the commands generated from URI Commands

I hope it helps :)

**Comment by Vinzent03** [comment]
I'm closing this, because I don't plan to implement this.
