### ISSUE TITLE
Bug? Using your plugin to trigger a command worked, now opens a new instance of Obsidian, but that in that new instance the command works?

### ISSUE THREAD

**Issue by ReaderGuy42** [Vinzent03/obsidian-advanced-uri#109]
I don't understand how this is working, but yesterday and the day before when I set this up it worked fine.

I have a link that opens the modal of the Book Search Plugin:
```
[New Book](obsidian://advanced-uri?vault=Books%20and%20Movies&commandid=obsidian-book-search-plugin%253Aopen-book-search-modal)
```

When I just opened my vault and clicked that link, it opened up a whole other instance of the vault. Then when I click the link in either of the two open vaults (the same vault) it went to the newly opened instance and the modal came up.

Any idea how I can keep it to a single instance of Obsidian?

Thanks!

**Comment by Vinzent03** [comment]
On which OS are you? What exactly do you mean with instance? Obsidian can't open the same vault multiple times. Do you mean a new window (doesn't have a sidebar)?

**Comment by ReaderGuy42** [comment]
I'm on Linux Mint, and I'm having trouble recreating the error as after restarting Obsidian a few times now, it seems to be working. But my impression was that it did open the whole vault a second time, including a sidebar. I'll wait and see if it happens again. Not sure if there's another issue because it keeps reindexing my vault. Thanks though!

**Comment by ReaderGuy42** [comment]
It's happening again. It is indeed a fully fledged second instance of that vault, including reindexing all the notes and asking for permission to use community plugins. Any ideas?

**Comment by Vinzent03** [comment]
I strongly doubt it's caused by my plugin. Do you have two Obsidian installations? Maybe one is registered for the URI and you use the other one.

**Comment by ReaderGuy42** [comment]
I'm fairly certain that it's only one installation, but I'll have a look. OK, well thanks anyway!
