### ISSUE TITLE
Would it be possible to have URIs for any section in settings?

### ISSUE THREAD

**Issue by YousufSSyed** [Vinzent03/obsidian-advanced-uri#110]
It would be great if I could access specific setting sections other than the ones list in the [documentation](https://vinzent03.github.io/obsidian-advanced-uri/actions/settings_navigation#obsidian-stores). I visited some frequently that aren't listed there.

**Comment by Vinzent03** [comment]
What exactly do you mean with section? Like `Behavior` under `Editor`?

**Comment by YousufSSyed** [comment]
Yes, as well as URI for community plugins and their sections.

**Comment by Vinzent03** [comment]
You can use the new `settingsection` parameter now.

**Comment by YousufSSyed** [comment]
@Vinzent03 I don't see the settingsection in documentation. I tried the following URIs but none of them work:

- `obsidian://advanced-uri?vault=Personal-Vault&settingsection=editor/behavior`
- `obsidian://advanced-uri?vault=Personal-Vault&settingsection=editor`
- `obsidian://advanced-uri?vault=Personal-Vault&settingsection=editor#behavior`

**Comment by Vinzent03** [comment]
Oh sorry, seems like I forgot to deploy the latest version. You need both `settingsid` and `settingsection`. Fixed now!

**Comment by YousufSSyed** [comment]
But how could I go to a specific setting subsection? Like `display` under `editor`?

By the way, can you add / enable a search bar in your documentation sites? It would make searching for things much easier.

**Comment by YousufSSyed** [comment]
That doesn't work for me. I also tried `obsidian://advanced-uri?vault=myvault&settingid=editor&settingsection=Behavior` but that only takes me to the top of the editor section.

**Comment by Vinzent03** [comment]
Are you on the latest version (1.32.0)? It works perfect for me.

**Comment by YousufSSyed** [comment]
Oh ... now it's working now. I'll leave it at that.

Also, I think you should add an explicit example in the [settings navigation page](https://vinzent03.github.io/obsidian-advanced-uri/actions/settings_navigation#setting-sections). 

`obsidian://advanced-uri?vault=<your-vault>&settingid=editor&settingsection=Behavior`
