### ISSUE TITLE
Feature Request: allow for creating commands to open specific URIs

### ISSUE THREAD

**Issue by YousufSSyed** [Vinzent03/obsidian-advanced-uri#112]
I would like to be able to open URIs via commands, by creating command shortcuts in the ribbon with Commander. I did lots of googling but couldn't find a way in Obsidian to open URLs or URIs with commands. You could add a section in settings with commands, where you can create commands by giving them a name and a URI to open. The command would be called with the name you give it.

**Comment by Vinzent03** [comment]
I don't think that's in the scope of this plugin. I haven't tried it, but [URI Commands](obsidian://show-plugin?id=uri-commands) should be what you are looking for.

**Comment by YousufSSyed** [comment]
I thought there wasn't a plugin like that, but there is and it works, thanks!

I looked back at the Google searches I made to find a plugin like that. When I did "Obsidian URL commands" nothing useful showed up nor showed that plugin, but searching "Obsidian URI commands" did. Isn't that weird?
