### ISSUE TITLE
FR: `eval` URI to run arbitrary command

### ISSUE THREAD

**Issue by chrisgrieser** [Vinzent03/obsidian-advanced-uri#114]
there are a lot of small one-liners calling the Obsidian API for which I currently create a templater script, bind it to a command, and then trigger it from outside Obsidian via the Advanced URI plugin. 

Example: `this.app.workspace.leftSplit.expand();` to show the left sidebar (Obsidian only has a toggle command built-in).

So I was thinking: How about an `eval` URI scheme which lets you run arbitrary javascript accessing the Obsidian API? This would cover a lot of these use cases and practically make a lot of smaller plugins redundant. (Obviously, add some warning signs that running arbitrary code can be dangerous.)

**Comment by Vinzent03** [comment]
I like the idea. I'm thinking about only allowing this with an additional toggle in the settings and of course adding an additional warning.

**Comment by Vinzent03** [comment]
Available via the new `eval` parameter!

**Comment by chrisgrieser** [comment]
On time for the 100k Downloads as well! 🥳

**Comment by Vinzent03** [comment]
I didn't even know :exploding_head:! A big part is probably because of your Alfred Workflow, thanks!

**Comment by chrisgrieser** [comment]
It has barely 10k downloads, so at least 90% of downloads is even without the workflow!
