### ISSUE TITLE
FR: openmode New Window

### ISSUE THREAD

**Issue by j-maffe** [Vinzent03/obsidian-advanced-uri#115]
Hi! I'd like to be able to open a new window of a specified note file without switching to the Obsidian window. The closest thing to this functionality is the popover option for the openmode. However, this falls a bit short as I'd like to, for example, see a new window when using a launcher like [Flow Launcher ](https://github.com/Garulf/Obsidian-Notes). Is this at all possible?

**Comment by Vinzent03** [comment]
I'm not exactly sure what you want. So basically like the `window` mode but keeping the main window in front? You want a real obsidian window and not just a small editor like the hover editor, right?

**Comment by j-maffe** [comment]
Please excuse my idiocity😅. Yes, like the `window` mode but without switching to the main Obsidianw window. This way, for example, while writing something in Chrome, I can open a window of a note in the vault, check something, and then close it without switching away from the original window.

**Comment by Vinzent03** [comment]
I'm sorry, but I don't think that's possible. I found no way to switch the window from withing Obsidian. I don't think that's technical possible. Obsidian gets focused before I can take any action, and removing the focus is as far as I know not possible.

**Comment by j-maffe** [comment]
Ohh that's too bad. Thanks for looking into it! :D
