### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by joshua-mcintosh** [Vinzent03/obsidian-advanced-uri#117]
Hello!

I work at a company that is particular about the code employees download and use, particularly with respect to some of the more virulent FOSS licenses (its policies are identical to https://opensource.google/documentation/reference/thirdparty/licenses). In some cases employees are disallowed from downloading the software in any form to avoid even the suspicion of misuse or worse, tainting it's products with said code (accident or not).

I've used this plugin a little bit to help tie my personal mobile use together, particularly with triggering URIs with Android's Tasker application. It also seems generally useful to me to have a more advanced URI system for knowledge management and automating tasks -- which would be helpful with my work vault :-) It looks like the plugin is marked as MIT in its package.json -- if this is the case, a committed file with the text of the license would be a positive confirmation on how you'd like the plugin to be used. If it's not actually MIT, no worries, but it would be useful to clarify the terms of the software with an explicit file.

**Comment by Vinzent03** [comment]
Thanks for letting me know. I added a MIT License
