### ISSUE TITLE
Can the plugin close a file/tab using the file name/path or UIID?

### ISSUE THREAD

**Issue by AniOhev** [Vinzent03/obsidian-advanced-uri#119]
I use the fabulous Streamdeck to open specific files in Obsidian. It would be fantastic if I could use the same method to close the file. Streamdeck has the functionality. I just need a URI schema that can be run on pressing the button. Might it be possible?

**Comment by AniOhev** [comment]
Thank you. It took me a few goes to work it out. For the benefit of others:

USING STREAMDECK MULTI ACTION SWITCH

OPEN FILE (1)

obsidian://advanced-uri?vault=MyVault&filepath=MyFolder/MyFile.md&viewmode=preview&openmode=tab

For added StreamDeck slickness Title = "Open" * make the title text green

CLOSE FILE (2)

obsidian://advanced-uri?vault=MyVault&filepath=MyFolder%252FMyFile.md&commandid=workspace%253Aclose

For added StreamDeck slickness Title = "Close" * make the title text red.

----------------

@Vinzent03 may I suggest that you consider adding 'close' documentation, as it current only includes 'open' examples.

Thanks for everything. Really appreciated.

**Comment by Vinzent03** [comment]
Closing tabs itself is not really a feature of this plugin, because it's just a use case for the command parameter, but I can add this as an example.
