### ISSUE TITLE
copying URI does not work on mobile

### ISSUE THREAD

**Issue by joellti** [Vinzent03/obsidian-advanced-uri#12]
The plugin works great in Obsidian Windows version but although it installs ok but no functionality is working in Obsidian Android version. I really like to see it working on mobile as well. Thanks again.

**Comment by Vinzent03** [comment]
Sorry to hear that it does not work, but on my site everything is working. What exactly happens if you open a link?

**Comment by joellti** [comment]
I just found an error on my side which caused the link not opening on mobile. It's working now. 

So the only thing not working is getting the link to the current note heading/block copied using "Copy Advanced URI" in the note menu or using "Advanced Obsidian URI: copy URI for file" in Command Palette. When I trigger either of these two action, nothing gets copied to the clipboard.

**Comment by Vinzent03** [comment]
Oh you are right. Will take a look.
