### ISSUE TITLE
[Question] Opening a different vault

### ISSUE THREAD

**Issue by lightningRalf** [Vinzent03/obsidian-advanced-uri#120]
Hello Vinzent,

First time I do this, so forgive me, still learning.
How do I open another vault?

Setup:
Folder: \\ds1621\xxx
in this folder i have two folders:
![image](https://user-images.githubusercontent.com/126403501/230536366-1436ecf0-4cff-444a-acd5-8a5840e17df3.png)

I want to integrate this Vault:
\\ds1621\xxx\PKM_Vaults_extern\EffortlessAcademicsManual\Greetings.md

into my Obsidian Vault, I tried the following:
(obsidian://open?vault=PKM_Vaults_extern/EffortlessAcademicsManual&file=Greetings.md)

Any suggestions? Maybe this could be expanded on in the documentation? Or is it there, and I just dont understand it?
Thanks in advance

**Comment by Vinzent03** [comment]
What do you mean by "integrate"? If `EffortlessAcademicsManual` is it's own vault, you don't need any path, but just the path.

**Comment by Vinzent03** [comment]
You don't need a path at all. Just the folder name itself.
