### ISSUE TITLE
[Request] Being able to edit YAML metadata

### ISSUE THREAD

**Issue by sacbegg** [Vinzent03/obsidian-advanced-uri#121]
I don't know if it's possible, although I've tried it in several ways, I would like to be able to access the frontmatter elements and change their value, for example, to do something like this 

obsidian://advanced-uri?daily=true&frontmatter={"mood": &data=happy, "exercice": &data=Push}&mode=append

It's just an idea, I don't know if it's currently possible but reading the documentation I can't find something similar.

Thank you very much for your attention and for your work!

**Comment by Chucky2401** [comment]
I'm also interested in this feature 👍

**Comment by Vinzent03** [comment]
There is now a way to edit specific frontmatter keys in 1.40.0. See the [documentation](https://vinzent03.github.io/obsidian-advanced-uri/actions/frontmatter) for more details.
