### ISSUE TITLE
open file after append

### ISSUE THREAD

**Issue by kimaldis** [Vinzent03/obsidian-advanced-uri#122]
I'm appending text to a note using Raycst and Advanced URI append parameter. Is there any way to open that file, if it's not alreay in view, once the append is done. I've tried running two uris but Racast appears not to like this in an action panel.

**Comment by Vinzent03** [comment]
Do you have the option "Open file on write" enabled in the plugin's settings?

**Comment by mmcguffi** [comment]
Im having the opposite problem -- I want to use raycast to append to my daily note, but it always opens my daily note when I append (I would like it to not open).`Open file on write` is not selected in the settings.

Im not sure if this is a raycast issue or an Advanced URI issue? And thanks for the all the effort making and maintaining this! It's much appreciated.

**Comment by Vinzent03** [comment]
I can't reproduce the issue. When disabling `Open file on write` it doesn't open the file for me.  Please ensure you are using the latest version.
