### ISSUE TITLE
Pass args or data

### ISSUE THREAD

**Issue by zanodor** [Vinzent03/obsidian-advanced-uri#126]
Greetings,

How to pass data to a command?  
I looked around in the docs, in vain.

I tried: `commandid=<command>&args=` and `commandid=<command>&data=` to no avail.

Z.

**Comment by Vinzent03** [comment]
What effect do you expect of additional data? Where/how should that be used?

**Comment by Vinzent03** [comment]
I don't know that plugin, but I guess it opens a modal to input text. I think that should be possible.

**Comment by Vinzent03** [comment]
So in your specific case, you would just need an enter to be automatically pressed when the modal comes up, because the right item is already selected?

**Comment by Vinzent03** [comment]
I don't plan to work on this issue, because it's very plugin specific. I suggest you to use the `eval` parameter (https://vinzent03.github.io/obsidian-advanced-uri/actions/miscellaneous) instead to run arbitrary javascript.
