### ISSUE TITLE
Support for multiple UID?

### ISSUE THREAD

**Issue by csss1234** [Vinzent03/obsidian-advanced-uri#127]
Sometimes I merge notes, and had two UIDs. I notice old links dont work when they are listed like this. Is there a workaround?

```
---
uid: dab591b3-36a8-4f47-a5de-ce537639a622
uid: e07bed73-30b6-46a5-af4d-8f2e7404c534
uid: aa863f84-0a3a-419d-af84-c5ba2c3b9912
---
```

**Comment by Vinzent03** [comment]
Multiple fields with the same key won't work, but I could add support for a list of uids. So you would write
```yaml
uid:
    - ...
    - ...
```
