### ISSUE TITLE
Write/Append not working

### ISSUE THREAD

**Issue by Ronacaodo** [Vinzent03/obsidian-advanced-uri#128]
Tried open below links on Chrome, but it just opened the Obsidian, the `data` has not been no appended nor written.
obsidian://advanced-uri?vault=R%20lib&filepath=03_project/Fleeting.md&data=Hello%2520World&mode=write
obsidian://advanced-uri?vault=R%20lib&filepath=03_project/Fleeting.md&data=Hello%2520World&mode=append

**Comment by Ronacaodo** [comment]
If I put the `Fleeting.md` to root, it is working:
obsidian://advanced-uri?vault=R%20lib&filepath=Fleeting&data=Hello%2520World&mode=append
But if put it in any other folder, it's not working.

**Comment by Ronacaodo** [comment]
@Vinzent03 
Obsidian Version 1.3.4 (Installer 1.3.4)
Advanced URI Version: 1.36.0

**Comment by Vinzent03** [comment]
Please try replacing your `/` with `%252F`.

**Comment by wealthychef1** [comment]
I have the same issue.  The following URI fails in Chrome and Safari with obsidian 1.3.7 and t

```
obsidian://advanced-uri?vault=wealthyvault&filepath=Planning%2520and%2520Organization%252FMeetings%2520and%2520Routines%252FComputer%2520Maintenance%252FUntitled.md?mode=append
```

If I rearrange the parameters so that `?mode=append` is first, it works perfectly: 
```
obsidian://advanced-uri?mode=append?vault=wealthyvault&filepath=Planning%2520and%2520Organization%252FMeetings%2520and%2520Routines%252FComputer%2520Maintenance%252FUntitled.md
```

**Comment by Vinzent03** [comment]
Your uri is wrong. Each `key=value` pair needs to be separated by `&`, but you are using `?` bevor the `mode=append`. 
https://vinzent03.github.io/obsidian-advanced-uri/concepts/schema

**Comment by wealthychef1** [comment]
> Your uri is wrong. Each `key=value` pair needs to be separated by `&`, but you are using `?` bevor the `mode=append`. https://vinzent03.github.io/obsidian-advanced-uri/concepts/schema

derp derp!  Thanks so much <blush>
