### ISSUE TITLE
[Feature Request] Add support for navigate by using UID

### ISSUE THREAD

**Issue by Quorafind** [Vinzent03/obsidian-advanced-uri#13]
It will be nice that obsidian advanced URI supports this feature (for people who don't want to install two plugins).

Refer: https://github.com/mrjackphil/obsidian-note-uid

**Comment by Vinzent03** [comment]
I don't really want to just copy his plugin idea. I will ask him about his opinion.

**Comment by mrjackphil** [comment]
@Vinzent03 No problem. We can merge that plugin into yours. 

But I should mention couple things:
- I was thinking to add "copy UID link" command palette functionality.
- There is an issue where it will not open the link when the Obsidian close since doesn't know the vault. I didn't fix that yet.

**Comment by Vinzent03** [comment]
Okay cool. Yeah adding a command is no problem. I have a helper function for that already. But I don't understand your second point.

**Comment by mrjackphil** [comment]
@Vinzent03 If you just copy-paste my code it'll not work when Obsidian is closed.  

![image](https://user-images.githubusercontent.com/16895902/125156657-47f83380-e16f-11eb-9192-8c9bd1eb7297.png)

**Comment by Vinzent03** [comment]
Oh yeah * had that problem too. You need to add the `vault` parameter too. Obsidian will handle this. In your code nothing changes.

**Comment by Vinzent03** [comment]
@mrjackphil Regarding the "copy UID URI" command. What exactly do mean. I would list all files by their filename with an id field in their frontmatter in a quick switcher as I am doing already with the normal "Copy URI for file" command.

**Comment by mrjackphil** [comment]
I think you can add an option in the settings to switch between `filepath/uid` which should be enough.

**Comment by Vinzent03** [comment]
@mrjackphil What's your plan with your plugin now?

**Comment by mrjackphil** [comment]
@Vinzent03 as with other my plugins as:
- backlinks in document
- zoom in header

the source still will be available and may will be helpful for someone. I'll put the deprecation note to the README with the link to your plugin. 

Other than that I'll put my effort to something else. Thanks for taking responsibility for supporting the plugin in your own hands 😃

Why are you asking?

**Comment by Vinzent03** [comment]
No problem. 
> Why are you asking?
 
Nothing specific. All fine.
