### ISSUE TITLE
Failed to open file using UID

### ISSUE THREAD

**Issue by Bananadurian** [Vinzent03/obsidian-advanced-uri#130]
When i use this url（`[test](obsidian://advanced-uri?vault=Notebooks&uid=20230518224225)`），the file opening failed！

---

**file frontmatter：**

```markdown
---
UID: 20230518224225
---
````
**console info:**

![image](https://github.com/Vinzent03/obsidian-advanced-uri/assets/53225469/6aa1b8bd-b4b7-4528-bb03-5ab1ac66a9bc)

**Obsidian Version**： 1.3.5（Win）
**Advanced URI Version**:：1.36.1

**Setting**：
![image](https://github.com/Vinzent03/obsidian-advanced-uri/assets/53225469/cc3bae21-6255-4355-9575-478ecd333a43)

**Comment by Vinzent03** [comment]
Thanks for reporting! Should be fixed in 1.36.2
