### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by vando** [Vinzent03/obsidian-advanced-uri#132]
Hello,

I can't run any command, it only opens the Obsidian app but doesn't run the command. 

The URI I'm using is

```
obsidian://advanced-uri?vault=obsidian-sync-icloud&commandname=Close%20current%20tab
```

Obsidian: 1.3.5 (same installer version)
OS: macOS Ventura (13.4.1)

Thanks in advance.

**Comment by Vinzent03** [comment]
Works fine for me when invoked in Obsidian. Where are you calling that uri? You may need to double encode, meaning:
```
obsidian://advanced-uri?vault=obsidian-sync-icloud&commandname=Close%2520current%2520tab
```

**Comment by vando** [comment]
If I open both URLs from a web browser I got the same error 🤷‍♂️

PD: Thanks for the quickly answer.

**Comment by Vinzent03** [comment]
Is the plugin enabled xD? Please share your console content (CTRL + SHIFT + I). It should contain an object of the received uri.

**Comment by vando** [comment]
Solved, plugin was disabled LOL.

Thank you!
