### ISSUE TITLE
Launching note on mobile pins it to sidebar / pane

### ISSUE THREAD

**Issue by csss1234** [Vinzent03/obsidian-advanced-uri#133]
I use a lot of open note url's in iOS shortcuts. Lately, obsidian will launch, but i dont see the note. Takes me a while to realize it got pinned to the left sidebar. This is new behavior as of the past couple weeks.

**Comment by Vinzent03** [comment]
Is it actually pinned so that it stayed at the side, when editing in the main split? Probably not, and it just stays in the sidebar. Make sure to close all of those files in the sidebar, because it refocuses them instead of opening a new one in the main split in that case.
