### ISSUE TITLE
[Feature Request] Allow search within a certain block: Jump to block first, then executing text searching.

### ISSUE THREAD

**Issue by XMB-7** [Vinzent03/obsidian-advanced-uri#135]
By adding the block as a parameter for searching, a sort of "link to any text (not just or not only link to a block)" can be somehow achieved, which is shown below. Even if the searched text is not unique in the block, it still at least locates nearby. 
On top of that I think it is quite feasible. Just jump to the specific block first, then executing text searching. And a corresponding command to copy the uri generated with selected text to search to clipboard is even more satisfying.

![](https://s3.bmp.ovh/imgs/2023/07/29/96024121b8456891.png)

**Comment by Vinzent03** [comment]
Isn't search from top to bottom. So the order of highlighting is independent of the cursor location?

**Comment by XMB-7** [comment]
To be honest, I was also very surprised that after jumping to the highlighted region, the search starts from the current position and goes downward. 
After discovering this feature, I realized by chance that it can achieve arbitrary text jumping than block-only jumping with advanced-uri, which circumvents the limitation of current markdown editors.

**Comment by Vinzent03** [comment]
I've added now support to execute block/heading navigation and search in one uri. I didn't add another command, because I don't think that feature is important enough for that, though.

**Comment by XMB-7** [comment]
Thank you for your time and effort. This feature really enhances my note taking experience.

However, currently searching is only executed if and only if the target file is the active file.
In other words, if the target file is opened but not active, or even not already opened, no searching will happen.

Additionally, when the target file is just active, I found that the navigation parameters seem not being considered, such as when `openmode=popover`.
The search just happens in the active page before navigating to the correct window/pane/popover.

**Comment by Vinzent03** [comment]
Hmm, works fine for me. Please share the uri you are using.

**Comment by XMB-7** [comment]
A link in my obsidian would be like `[✨](obsidian://advanced-uri?vault=KnowledgeBase&uid=20230707_182225&openmode=popover&block=0l2r7x&search=I hope to help you develop intuition about what AI can and cannot do.)`

This following gif shows searching happens in the active page rather than the popover.
![Image_20230808_203434](https://github.com/Vinzent03/obsidian-advanced-uri/assets/65625632/19d6cec6-21eb-4667-8cf0-4f2880b72b3c)

This following gif shows, with the same uri, when the target file is not already opened, first no popover but a tab is falsely invoked, second searching does not happen after navigation.
![Image_20230808_204210](https://github.com/Vinzent03/obsidian-advanced-uri/assets/65625632/cfd3c279-6adc-409e-b42b-eea429678b11)

**Comment by Vinzent03** [comment]
Still can't reproduce. What is your "current version" and "Installer version" in settings -> about? The Advanecd Uri version is 1.37.0 and Hover Editor 0.11.13, right?

**Comment by XMB-7** [comment]
I just tested in the provided Obsidian sandbox vault but also failed to reproduce this issue, so there may be a plugin conflict.
Since I have over 70 plugins enabled, it will take me some time to find out which one is causing the problem.

Apologies for not thoroughly testing this before submitting an issue.
