### ISSUE TITLE
Cannot navigate to a block with `&openmode=popover`.

### ISSUE THREAD

**Issue by XMB-7** [Vinzent03/obsidian-advanced-uri#137]
For example, `obsidian://advanced-uri?uid=20230727_225033&openmode=popover` works well, 
but `obsidian://advanced-uri?uid=20230727_225033&openmode=popover&block=j1zrwd` fails to jump to the block in a popover (no popover being invoked).

I'd appreciate it if this feature could be supported.

**Comment by Vinzent03** [comment]
I intentionally disabled block and heading support for popover before, but with some minor fixes now, everything should work.
