### ISSUE TITLE
Bug : Corruption of Video Files When Using Advanced URL Plugin on MP4 Formats

### ISSUE THREAD

**Issue by Tsuki-Gor** [Vinzent03/obsidian-advanced-uri#139]
Bug Description:
When using the "Advanced URL" plugin in Obsidian's sidebar to right-click on a video file (such as an mp4 format) and then selecting the "Add Advanced URL" button, the plugin attempts to add a YAML header to the beginning of the video file. This results in the video file becoming corrupted and consequently leads to loss of video data.

Expected Behavior:
To prevent unintentional corruption of video files, it is suggested to consider disallowing the use of the "Advanced URL" plugin on mp4 files, or to implement a safeguard that prevents the addition of YAML headers to video files.

Steps to Reproduce:

Open Obsidian.
In the sidebar, locate and right-click on a video file (e.g., mp4).
Select the "Add Advanced URL" plugin button.
Observe that the video file becomes corrupted after the plugin operation.
Environment:

Obsidian version:1.3.7
Operating system: windows 10
Additional Information:

The corruption caused by the "Advanced URL" plugin has led to loss of valuable video data. It is crucial to ensure that plugin operations do not damage existing file formats.

**Comment by Vinzent03** [comment]
I'm really sorry, this happened to you. The core file recovery plugin, might have a copy of your media files. Which plugin version are you using? In the latest version, that should already be fixed.

**Comment by Tsuki-Gor** [comment]
Thank you for your quick response!I've checked my plugin version, and it was indeed 1.33.0.  I've upgraded to the latest version, and the issue is now resolved. Your dedication to addressing this and improving the plugin is truly appreciated. Looking forward to more great updates from you!
