### ISSUE TITLE
How To Send Data Without Opening Obsidian

### ISSUE THREAD

**Issue by aplegs** [Vinzent03/obsidian-advanced-uri#140]
What I wanted to do is this: create a file without Obsidian popping up/coming to the foreground(I am making the request from my browswer).
I tried the following uri:
obsidian://advanced-uri?&filepath=test&openmode=silent

# What happens?
This opens up Obsidian but does not create a file named "test"

**Comment by Vinzent03** [comment]
Sorry, but it's not possible to use an URI and not focus/open Obsidian. The silent parameter is only used to not open a file in a pane, when e.g. writing to a file.

**Comment by aplegs** [comment]
Understood, thank you for your response.
