### ISSUE TITLE
I want to be able to link blocks with a unique ID

### ISSUE THREAD

**Issue by jiajiala** [Vinzent03/obsidian-advanced-uri#141]
I want to be able to link blocks with unique ids. obsidian blocks do not have unique ids

This means that the block cannot be moved between different files, and once it is moved, all links to the block will break

Because whether the link comes with ob or is generated by the Advanced URI, the link of the block is based on the body of the file

As A result, a block cannot be moved from document A to document B during information reconstruction without all related links breaking

Blocks cannot flow smoothly between documents, so it is necessary to ensure that all blocks are established in a document in a library at the beginning

This link structure makes it difficult to reconstruct later notes

Make links based on unique ids, not based on libraries and files as upper-level paths

For example, obsidian://open? vault= block ID

Instead of obsidian://open? vault= library name &file= folder name %2F File name

Also non-obsidian ://advanced-uri? vault= library name &block= block ID&uid= file ID

**Comment by Vinzent03** [comment]
You always have to specify a specific vault or the last one is used. This plugin cannot control that behavior. But you can now omit the file specification and only use the `block` parameter.
