### ISSUE TITLE
1.38.0 - if cursor is on the line of the heading, "copy URI for current file" command includes heading link

### ISSUE THREAD

**Issue by luckman212** [Vinzent03/obsidian-advanced-uri#142]
Seems that if cursor is on the line of the heading, then the output is what you would get from "copy URI for current block"

example

```md
# Foo
^---cursor here, execute "Advanced URI: copy URI for current file" command 

abc

# Bar

xxx
```

expected:

```
obsidian://advanced-uri?vault=Main&uid=1a235bde-4067-4958-bb13-8eb0d5349650
```

actual:
```
obsidian://advanced-uri?vault=Main&heading=Foo&uid=1a235bde-4067-4958-bb13-8eb0d5349650
```

**Comment by luckman212** [comment]
Hmm, actually I see "copy URI for current block" generates a unique ID and a `block=` parameter. So maybe this is actually intended behavior?

**Comment by Vinzent03** [comment]
Yeah this is the intended behavior to automatically get a link to the current heading in the note. The command for current block is different and goes further by creating a block reference.

**Comment by luckman212** [comment]
Maybe would be cool to have a separate command or a toggle to make the command distinctly include the heading link or not. (in my case, most of the time I don't actually want it)

**Comment by Vinzent03** [comment]
Hmm I think there are already enough commands and that's not really worth to add another. The heading is only included if the cursor is in the line of the heading, so why don't put the cursor somewhere else?

**Comment by luckman212** [comment]
Understood. No problem. Just have to get used to it. Or, I can always just trim the parameter from the copied URL after.

**Comment by luckman212** [comment]
Not sure when it became possible to add custom formats, but I noticed that's available now. 

I used this to get the command I wanted (never include `heading=`).

```
obsidian://adv-uri?uid={{uid}}
```

If only it was possible to bind this directly to a hotkey!

**Comment by Vinzent03** [comment]
Oh yeah eventually I decided to add this feature. If you only have one custom format configured it automatically selects it if that helps.

**Comment by luckman212** [comment]
Yes, that does help! At least I can bind that command. thanks 👍
