### ISSUE TITLE
Open block doesn't bring block into view

### ISSUE THREAD

**Issue by cpt-n3m0** [Vinzent03/obsidian-advanced-uri#145]
On obsidian 1.4.12, when I open a link in the format 
`<a href="obsidian://open?vault=vault&file=test.md&block=ID1661787459110"> test </a>`

The file is opened but the block is not brought into view and highlighted like the native block link behaviour even though the console shows that the appropriate URL action has been received with the right block id.

**Comment by Vinzent03** [comment]
Your uri is wrong. You are using the obsidian action `open` and not the `advanced-uri` from this plugin. Take a look at the [documentation](https://vinzent03.github.io/obsidian-advanced-uri/actions/navigation).
