### ISSUE TITLE
Issue with Executing Advanced URI Using QuickAdd in Obsidian

### ISSUE THREAD

**Issue by lucasbcgeo** [Vinzent03/obsidian-advanced-uri#150]
Hello everyone,

I'm encountering an issue with the QuickAdd plugin in Obsidian and need some assistance. I have set up an Advanced URI to trigger a specific action in QuickAdd, but when I click on the URI, nothing happens.

Here's the URI I'm using:
`obsidian://advanced-uri?vault=LucasCofre1.4.1&choiceid=2eb27d4b-e1f9-47ee-8419-e85f4d49b581`

This URI is meant to trigger an action(macro/script .js) named "NotaPassageira-criação" that I have configured in QuickAdd. The `choiceid` corresponds to this action, and the vault name is correct.

However, when I click on this URI link, there is no response or action triggered in Obsidian. I have checked the following:

- The Obsidian app is open and running.
- The `choiceid` matches the configuration in QuickAdd.
- I am using the latest versions of both Obsidian and the QuickAdd plugin.
- Permissions for opening links between applications are allowed on my operating system.

Despite these checks, the issue persists. I'm unsure if I'm missing a step in the setup or if there's a technical glitch. Any insights or suggestions on how to resolve this would be greatly appreciated.

Thank you in advance for your help!

Best regards,
Lucas

**Comment by iT-Boyer** [comment]
The author provides two ways to start.
`obsidian://advanced-uri?vault=<YOUR_VAULT_NAME>&commandname=QuickAdd: Run QuickAdd`

https://quickadd.obsidian.guide/docs/Misc/AHK_OpenQuickAddFromDesktop

**Comment by lucasbcgeo** [comment]
> The author provides two ways to start. `obsidian://advanced-uri?vault=<YOUR_VAULT_NAME>&commandname=QuickAdd: Run QuickAdd`
> 
> https://quickadd.obsidian.guide/docs/Misc/AHK_OpenQuickAddFromDesktop

The author provides one way to use hotkeys and another one to install advanced uri. I can't see how one of these possibilities could help me.

**Comment by lucasbcgeo** [comment]
> > The author provides two ways to start. `obsidian://advanced-uri?vault=<YOUR_VAULT_NAME>&commandname=QuickAdd: Run QuickAdd`
> > https://quickadd.obsidian.guide/docs/Misc/AHK_OpenQuickAddFromDesktop
> 
> The author provides one way to use hotkeys and another one to install advanced uri. I can't see how one of these possibilities could help me.

Uncaught (in promise) SyntaxError: Unexpected identifier 'Input'
    at eval (<anonymous>)
    at getUserScript (plugin:quickadd:9663:24)
    at async MacroChoiceEngine.executeUserScript (plugin:quickadd:12022:24)
    at async MacroChoiceEngine.executeCommands (plugin:quickadd:11995:9)
    at async MacroChoiceEngine.run (plugin:quickadd:11988:5)
    at async ChoiceExecutor.onChooseMacroType (plugin:quickadd:18928:5)
    at async ChoiceExecutor.execute (plugin:quickadd:18891:9)
    at async Object.callback (plugin:quickadd:19599:11)
    
    
    =(

**Comment by Vinzent03** [comment]
I can't follow you. What exactly are you trying and what do you think is the issue with this plugin(Advanced URI)? Just pasting a stack trace which only contains function calls from QuickAdd doesn't help.
