### ISSUE TITLE
Editing without opening file

### ISSUE THREAD

**Issue by Jeromandres** [Vinzent03/obsidian-advanced-uri#152]
Hello

I am looking for a way to open Obsidian through an advanced URI command without changing the focus page in Obsidian (w/o opening the file in front concretely).

Context

- I am using Advanced-URI to add links to actions in Kanban.
- Hence calling Obsidian from within Obsidian -- easiest way I found to prepend links to a page in javascript.
-  It results into the Kanban file getting open in front, which is cumbersome as I often want to stay with the file I launched my command.

In the end, it would mean opening a link with Advanced-URI without changing the current focus open file -- not opening the target file of the command. I did not find a way to do it inside the documentation.

Thank you for your support, regards

**Comment by Vinzent03** [comment]
May you try setting the `openmode` query parameter to `silent`(https://vinzent03.github.io/obsidian-advanced-uri/concepts/navigation_parameters#open-mode). This should edit the file as described by the writing mode (https://vinzent03.github.io/obsidian-advanced-uri/actions/writing), but not open the file.
