### ISSUE TITLE
Is it possible to run 2 (or more) commands from one URI?

### ISSUE THREAD

**Issue by gasparschott** [Vinzent03/obsidian-advanced-uri#155]
I've attached a command to a link in the right-split that changes a setting in the note in the root-split when the link is clicked. 

This works, but the focus remains on the right-split. 

I'd like to add a second command (to execute immediately after the first command) to the uri that would restore the focus to the root-split note. 

So, is it possible to run multiple commands from the same uri? Thanks.

**Comment by gasparschott** [comment]
Never mind; I figured out how to do it.

**Comment by luckman212** [comment]
@gasparschott would you mind sharing how you did it?
