### ISSUE TITLE
trouble with command ID/name

### ISSUE THREAD

**Issue by seatrout** [Vinzent03/obsidian-advanced-uri#159]
I am confused by the difference between a command ID and the command name.

In particular, I want to call the Pandoc extension command to export a file as word (because it uses Obsidian's rendered markdown, and plain pandoc is bad at footnotes, block quotes, and so on). 

But none of the pandoc extension's commands show up using this extension's `copy command ID` 

Do I then use `command name` instead? How much do I have to escape that string?

**Comment by Vinzent03** [comment]
I can't reproduce your issue. Are you using the `Advanced URI: copy URI for command` command? You first specify the file and afterward select the command to execute.

**Comment by seatrout** [comment]
To reproduce my issue, just try to use the `Advanced URI: copy URI for command` on commands such as `Pandoc Plugin: Export as Word Document (docx)` — they are not shown; in fact none of the pandoc subcommands are. So my question was how do I pass in `Pandoc Plugin: Export as Word Document (docx)` as a command? I tried escaping it in various ways and none of them seemed to help. 
It's possible to work around this — I finally wrote a script to call pandoc externally and to mimic the tricks the extension uses to reproduce what we see on screen in Obsidian. So it's a low priority. But it is reproducible.

**Comment by Vinzent03** [comment]
Well, it still works perfectly fine for me. Are you using the latest version of both plugins?
Either way, you can try the following uri.
```
obsidian://advanced-uri?commandid=obsidian-pandoc%253Apandoc-export-docx
```

**Comment by seatrout** [comment]
ah! Thank you: so it needs

   1. The separate words joining with hyphens
   2. the colon double escaped.

This wasn't clear from the documents. Perhaps it could be made clearer. I
had read them to mean that all the spaces in a command name had to be
escaped, not replaced with hyphens.



-------------------
Andrew Brown
Writes for people
mobile: +44-(0)7968-945618

**Comment by Vinzent03** [comment]
That's not the case. There is a difference between name and id. The one I gave you is using the command id and not the name. The id contains hyphens as defined by the plugin developer.
