### ISSUE TITLE
Double Encoded URI

### ISSUE THREAD

**Issue by sigmoid-azoth** [Vinzent03/obsidian-advanced-uri#16]
It looks like URIs must be double encoded. Is this intended behavior?

### Encode examples

Raw
`<\\%`

Encoded
`%3C%5C%5C%25`

Double Encoded
`%253C%255C%255C%2525`

### Plugin test example

Run this in your console

```javascript
 open("obsidian://advanced-uri?vault=" + encodeURI(app.vault.adapter.basePath.split("\\").reverse()[0]) + "&searchregex=" + encodeURI(encodeURI(/<\\%/g)) + "&replace=" + encodeURI(encodeURI("<%")))
```

On this content

`<\% tp.frontmatter.field %>`

---

If this is intended behavior, it may be helpful to others if the README page mentions it.

**Comment by Vinzent03** [comment]
I noticed that you need to encode the parameter value(`encodeURIComponent()`) and the whole uri (`encodeURI()`). You are right, it's better to mention this.
