### ISSUE TITLE
[Feature Request] Scroll to Buttom|滚动到末尾

### ISSUE THREAD

**Issue by Jiang10086** [Vinzent03/obsidian-advanced-uri#168]
调用Advanced URI在文件后面追加内容时，光标会跳到文档末尾，但是不会滚动到最下面，看起来有些局促
When calling Advanced URI to append to a document, the cursor jumps to the end of the document, but does not scroll to the bottom, which seems a bit cramped.

![image](https://github.com/Vinzent03/obsidian-advanced-uri/assets/67213568/c79c3139-8826-4785-b4ad-cfeba9452e3b)

这是Advanced URI的默认效果
This is the effect of Advanced URI

![image](https://github.com/Vinzent03/obsidian-advanced-uri/assets/67213568/7d3af258-a299-4dd0-8518-d71b93ccc2b5)
要是能加个参数，像这样滚动到页面末尾就好了，现在只能手动
It would be nice if I could add a parameter to scroll to the end of the page like this, right now I can only do it manually

我用的URI：obsidian://advanced-uri?vault=Obsidian%20Vault&filepath=xxx.md&mode=append&viewmode=live
The URI I use: Obsidian://advanced-uri?vault=Obsidian%20Vault&filepath=xxx.md&mode=append&viewmode=live

**Comment by Vinzent03** [comment]
You can now use the `line` parameter to set the cursor in a specific line. Use 1 for the first line and any high number for the last line.
