### ISSUE TITLE
How to make an entry under the header or callout using “Advanced URI” plugin?

### ISSUE THREAD

**Issue by from777** [Vinzent03/obsidian-advanced-uri#170]
I add an entry to the end of a note using this link
'obsidian://advanced-uri?filepath='+filepath+'&data='+new_data+'&mode=append&openmode=silent'

Is it possible to add the record not at the end of the document, but under some specific header or callout ?

**Comment by Vinzent03** [comment]
Yes you should be able to just add the `heading` parameter to append after a heading as stated in the [documentation](https://vinzent03.github.io/obsidian-advanced-uri/actions/writing)
Appending to a callout is not supported.

**Comment by Vinzent03** [comment]
Appending to a callout is not planned, but you can append/prepend to a line by specifying the `line` parameter with the line number. https://vinzent03.github.io/obsidian-advanced-uri/actions/writing
