### ISSUE TITLE
Is it possible to click on confirm button when executing command with advanced uri?

### ISSUE THREAD

**Issue by AlexW0lf1** [Vinzent03/obsidian-advanced-uri#174]
Let's say I want to execute Export to Pdf command from powershell

URI looks like this

obsidian://advanced-uri?vault=Project_Obsidian&filepath=URI.md&commandid=workspace%253Aexport-pdf

After executing command I see a modal asking for additional options and button "Export to pdf"

Can I add additional arguments to this uri, so I won't have to press button manually?

**Comment by AlexW0lf1** [comment]
Right now I'm using ?eval argument to execute some js and manipulate DOM to select options and click button, but this seems like a bad solution. Would have been better if I could pass all arguments through uri

**Comment by Vinzent03** [comment]
It's now available in v1.43.0 :tada: Just add `confirm=true` as parameter to the command uri. It looks for the first main button and clicks it.

**Comment by Vinzent03** [comment]
I tried that myself as well, but couldn't find a way so far.
