### ISSUE TITLE
URI for close vault

### ISSUE THREAD

**Issue by Nebucatnetzer** [Vinzent03/obsidian-advanced-uri#18]
Would it be possible to add a URI for closing a vault?
Currently it's not really possible to switch between vaults.
One workaround I could think of would be to close the current vault first before opening it.

**Comment by Vinzent03** [comment]
So you want to open a file in vault A. Then close vault A and open another file in vault B?

**Comment by Nebucatnetzer** [comment]
Exactly yes.
Or to be more specific write a file in vault B.
I have one vault with my usual notes in it and another one in which I save all my read articles as a Markdown file.
The workflow which currently isn’t working on mobile (specifically iOS) goes usually like this:
1. Open a file in my notes vault (e.g. groceries list)
2. Later read an article and try to save it with an iOS Shortcut in the articles vault.

Obsidian now can’t switch to the articles vault and just shows me the previously opened note from the notes vault.
My idea is now to create an Shortcut which works like this:
1. Close the currently active vault
2. Open the required vault (e.g. articles)
3. Perform the action in the vault (e.g. write a new article note)

**Comment by Vinzent03** [comment]
I have done a bit of research and I don't think closing the vault will help. Even if you are in the vault switcher, you can't open another vault per URI.

**Comment by Nebucatnetzer** [comment]
I thought that might be the case in my tests.
Ah well I merged the two vaults back together, in the end it is anyway all part of my knowledge.
Thank you for having a look at it.
