### ISSUE TITLE
No issue, just a shout :)

### ISSUE THREAD

**Issue by moremeyou** [Vinzent03/obsidian-advanced-uri#180]
Hey there,
This plugin slaps. It's key to my rapid idea capturing. I dropped a shout in a demo for my own plugin. No need to shout back. Just thought I'd give you a heads up :)

https://youtu.be/Q6_bC2aGKQk?si=CRbE7DMZSJCekm4i

**Comment by Vinzent03** [comment]
Hey, thank you! Great you like it and is useful for your workflow!
