### ISSUE TITLE
[Feature Request] Open file to specific offset

### ISSUE THREAD

**Issue by waynehoover** [Vinzent03/obsidian-advanced-uri#181]
In addition to opening a file at a specific line number and column, it would be very helpful to set the cursor at a specific offset in the file and scroll that into view. This is useful when using the [Omnisearch HTTP server API](https://publish.obsidian.md/omnisearch/Public+API+%26+URL+Scheme#HTTP+Server+API) as it only returns the offset to the word in the file.

For reference, [here](https://github.com/scambier/obsidian-omnisearch/blob/c34503f1cd89a5e6bd1813cc608b698ced890189/src/tools/notes.ts#L38-L46) is how Omnisearch implemented this functionality internally. And [here](https://github.com/luckman212/obsidian-open-to-offset/) is a plugin that registers uri scheme specifically for jumping to an offset in a file

Thanks so much.

**Comment by Vinzent03** [comment]
Is now available in v1.43.0 :tada: via the `offset` parameter.
