### ISSUE TITLE
IS THIS A KIND OF FASCİSM TO OPEN SOURCE?!

### ISSUE THREAD

**Issue by Medullitus** [Vinzent03/obsidian-advanced-uri#185]
You are making an open source pluging. But it won't work on LINUX unlike Windows. What's this dilemma?! Are you serious ?!?!

**Comment by Vinzent03** [comment]
I don't know what's wrong with you, but if you're actually interested in fixing your issue, try creating a new issue without being rude and provide actual helpful information about your case. I'm on Arch btw, so it definitely works on Linux.

**Comment by Medullitus** [comment]
Okay, I'm calm now. So, let me start over.

First of all, congratulations on using free software. However, unfortunately, your plugin doesn't work correctly on Linux as it does on Windows.

I use the Readitlater plugin in Obsidian. I'm including the link below. The plugin requires your plugin. But unfortunately, due to the issue on Linux, I can't save web pages with Readitlater. If you want, you can try Readitlater yourself to confirm the problem.

Thank you! And I apologize for the subject line. After trying so hard to solve the problem and failing, I ended up using that title. I know that's not an excuse, but I apologize anyway.

https://github.com/DominikPieper/obsidian-ReadItLater

**Comment by Vinzent03** [comment]
Are you sure the issue lies in this plugin and not the ReadItLager plugin? By just saying it's not working, I guess Obsidian doesn't even get launched by the uri or no uri is called at all. That's nothing the plugin can control.
