### ISSUE TITLE
Vault not found if using the URI from another vault

### ISSUE THREAD

**Issue by IanElsinga** [Vinzent03/obsidian-advanced-uri#186]
If a link is created using the vault name and that link is pasted in another vault, the link will not work. It says `cannot find a vault...`. It does work if run from outside Obsidian, from a windows run prompt for example. 

If a link is created using the vault ID instead of the name, then the links work in both cases. 

Can you or do you support using vault names in the link when clicking it from another Obsidian vault?

**Comment by Vinzent03** [comment]
The plugin doesn't handle the `vault` parameter at all. That's handled by Obsidian. Please try the same with the default [Obsidian URI](https://help.obsidian.md/Extending+Obsidian/Obsidian+URI). If the issue persists, please open a bug report in the Obsidian forum.

**Comment by IanElsinga** [comment]
Thanks for the quick reply, @Vinzent03. 
I did try with the default Obsidian link which contains the vault name (not ID), and that works fine from a different vault. But I see what's happening. The following manually adjusted link works from vault to vault: 

`obsidian://adv-uri?vault=Powertranz%20Docs&filepath=Docs%2FRecurring.md&heading=Hookdeck`

However, when I choose  `Advanced URI: Copy URI for current file` from the command pallet, it puts this in my clipboard, which doesn't work: 

`obsidian://adv-uri?vault=Powertranz Docs&filepath=Docs%2FRecurring.md&heading=Hookdeck`

So it's only an issue with vault names containing spaces: the Advanced URI copy isn't replacing them with `%20`.

**Comment by Vinzent03** [comment]
Thanks for the investigation. Should be fixed now.

**Comment by IanElsinga** [comment]
Works. Thanks!
