### ISSUE TITLE
Copy URI for Command produces non-functioning URI

### ISSUE THREAD

**Issue by Glint-Eye** [Vinzent03/obsidian-advanced-uri#187]
When I use the command  for "Copy URI for Command" and then afterwards wrap the whole thing in a markdown link for a clickable link, the command won't execute. After some testing i found that the Starting part of the URI: "obsidian://**adv**-uri..." doesn't resolve the command. Only if i manually change it to "obsidian://**advanced**-uri..." the command wrapped in a markdown link is resolved on click.

**Comment by Vinzent03** [comment]
I can't reproduce your issue. Are you generating and clicking the URI on the same device? If not make sure all devices have the latest plugin version. The new adv-uri schema is new and uses less encoding. Please share your whole uri.
