### ISSUE TITLE
open daily note with heading not always working

### ISSUE THREAD

**Issue by goldenages1989** [Vinzent03/obsidian-advanced-uri#19]
with parameter mode it works. otherwise it won't work.

**Comment by Vinzent03** [comment]
So you want to navigate to the header? This is currently not supported. See [README](https://github.com/Vinzent03/obsidian-advanced-uri#daily-notes). But this should be an easy feature.

**Comment by goldenages1989** [comment]
> So you want to navigate to the header? This is currently not supported. See [README](https://github.com/Vinzent03/obsidian-advanced-uri#daily-notes). But this should be an easy feature.

so this feature will be added in future release?

**Comment by Vinzent03** [comment]
I closed it, because I released it. Just install the new version. Sorry I should have mention this.

**Comment by goldenages1989** [comment]
That was a quick response. Thank you very much for your work.
