### ISSUE TITLE
URI to block is not always working

### ISSUE THREAD

**Issue by boredPanda96** [Vinzent03/obsidian-advanced-uri#192]
I am trying to open links of the type `obsidian://adv-uri?vault=prep&amp;uid=f3556e68-bfbe-4033-a3aa-5e9f1192ec2d&amp;block=block-id`, however except if the file is already open, the correct block is not highlighted

I am able to see following errors in the console

![CleanShot 2024-12-08 at 10 14 27@2x](https://github.com/user-attachments/assets/faf8b3e8-fe69-4aec-98c4-a882fb53ea5c)

![CleanShot 2024-12-08 at 10 14 45@2x](https://github.com/user-attachments/assets/3cf50bff-4b45-4ac4-bf69-becfcf1c0d43)

Versions - 
Obsidian → 1.7.7
Advance URI → 1.44.2

**Comment by boredPanda96** [comment]
make this better for github issue comment

I think I figured out the reason → Keys in JS objects are case sensitive

`n.block` is `Women-CPR`

whereas `this.app.metadataCache.getFileCache(e.file).blocks` has `women-cpr` as key with `id` as `Women-CPR`

I am not able to figure out ow it is working on the first open on the file though

**Comment by Vinzent03** [comment]
Thanks for the bug report. The blocks are now handled case-insensitive. This is not released yet, though.
Please note that there is no need to ping me after just 3 days of no response to this issue.

**Comment by boredPanda96** [comment]
Thank you @Vinzent03 for implementing the case-insensitive block handling. I appreciate your quick resolution of this issue and apologise for the unnecessary follow-up ping. Looking forward to the release!

**Comment by boredPanda96** [comment]
@Vinzent03 any plans to do a release soon? Otherwise I will use a local build. Thanks

**Comment by Vinzent03** [comment]
Thanks for the reminder. It's now released in 1.44.3!
