### ISSUE TITLE
[FEAT?] Add daily note support

### ISSUE THREAD

**Issue by Quorafind** [Vinzent03/obsidian-advanced-uri#2]
# WHAT

If I want to quick add data to daily note, it will be hard to change the date everyday, OR i should write a script for myself.

**But I think it is hard to code this feature, so this issue is just an inspiration **

# HOW TO

Argenos had coded a similiar feature before. https://github.com/argenos/nldates-obsidian

# HOW IT COULD BE

It would be nice that make a parameter like daily?

like `obsidian://advanced-uri?vault=<test-vault>&timepath=%DD%%MM%%WW%%20Weekly%20Note&data=<text>&mode=append`

**Comment by Vinzent03** [comment]
Good idea. What do you want to achieve with `timepath`?

**Comment by Quorafind** [comment]
@Vinzent03 I don't know if it is doable, but I want to use my daily note to capture my ideas and TODO, for example , I am using my daily note to capture todo. Don't need to open Ob and then input data.

Just double click Ctrl to call listary and then input what I want. 

And also, I could make daily note as a read later center, though it is not so convinent now, but I have use the feature to append URL\Text\Current Time and track and so on....

I think if it is doable, I could give you another inspiration:
- Add a configurable path in setting

like: timepath:  YY-MM-DD dailynote

**Comment by Vinzent03** [comment]
I still don't understand your aim with `timepath`. Just to tell the plugin where the daily notes are or to insert dates based on this moment format?

**Comment by Quorafind** [comment]
@Vinzent03 Hmmmm, if you have another better solution, please ignore what the `timepath` .... 😂

**Comment by Vinzent03** [comment]
To clarify. You aim is to append text to the today's daily note?  Normal text or has it to support extra features?

**Comment by Quorafind** [comment]
@Vinzent03 Yes, my aim is to append text to the today's daily note

**Comment by Vinzent03** [comment]
I hope the new [release](https://github.com/Vinzent03/obsidian-advanced-uri/releases/tag/0.2.2) fits your needs.

**Comment by Quorafind** [comment]
@Vinzent03 it works so good ! Thanks for your hard job!
