### ISSUE TITLE
Check if note exists using Advanced URI?

### ISSUE THREAD

**Issue by VKondakoff** [Vinzent03/obsidian-advanced-uri#20]
Hello!

From time to time you need to know if a note exists already to decide if you need to write or append to it. On desktop I can use AppleScript or tools like Keyboard Maestro to check if note exists before writing (I'm on Mac). But on iOS there is no easy way to do the same using Shortcuts.
Any chance you can implement checking for note existence with Advanced URI?

Thanks a lot!

**Comment by Vinzent03** [comment]
I guess, a better solution for your problem is a new mode to append if the file exists and write if not.

**Comment by VKondakoff** [comment]
Thanks for your answer. 
There is usually different data for writing/appending depending of the file existence. For example: if file does not exist write header, some tags and links and some data. If file exists already, just append some new data.
So, checking for existence is needed to decide which data to write/append.

**Comment by Vinzent03** [comment]
Ah okay I understand. But how should I return the info? I don't think the url can return data.

**Comment by VKondakoff** [comment]
Ah… I was hoping there are some responses, like in Get, which is used to access the APIs: https://support.apple.com/en-in/guide/shortcuts/apd58d46713f/ios

**Comment by Vinzent03** [comment]
No that's not possible. A way would be to copy the result to clipboard.  Would that be ok? What value would you prefer?

**Comment by VKondakoff** [comment]
Wow! That's great! Maybe just zero or one? `1` if file exists, `0` if file not exists?

**Comment by Vinzent03** [comment]
Available in new release!

**Comment by FelipeRearden** [comment]
@Vinzent03 and @VKondakoff !

Would you mind sharing an URI as an example for this new feature ? I wanna learn how to use :)

Thanks and have a great day :)

**Comment by Vinzent03** [comment]
It should be clear from the documentation in the README, but an example would be `obsidian://advanced-uri?vault=myVault&filepath=my-file&exists=true

**Comment by FelipeRearden** [comment]
Thank you @Vinzent03 !

Now I get it with your example! 

If the file exists in the vault the value `1` is copied to the clipboard; 
if not `0` is copied to the clipboard.

Thanks again!
