### ISSUE TITLE
open file in new pane?

### ISSUE THREAD

**Issue by cedardocster** [Vinzent03/obsidian-advanced-uri#21]
Hi, I have this command using your plugin with a bash script that does work to open a file:

`xdg-open "obsidian://advanced-uri?vault=${VAULT2}&filename=${FILE4}"`

Is there a way to force it to open the file in a new pane?  I'm usually viewing my files in obsidian but if they're not already linked in the current file calling them up with a rofi (bash) script to open them.  99% of the time I'd like to see the new file beside the current one, not replacing the current one.  Is this possible using your plugin (or any other way you can think of?)

I see a reference to your other plugin "obsidian-shortcuts-for-starred-files" that has that, but not sure if this functionality is also in the obsidian-advanced-uri plugin or not

thank you!
- Dave

**Comment by Vinzent03** [comment]
There should be a setting in the settings pane.

**Comment by cedardocster** [comment]
Thank you - I see it now (sorry, new to Obsidian)

**Comment by Vinzent03** [comment]
No problem. Can I close this now?

**Comment by distbit0** [comment]
Hmm I also can not see any setting in the advanced uri plugin settings for specifying a default openmode. Where might I find this? many thx

![image](https://github.com/Vinzent03/obsidian-advanced-uri/assets/10890247/45846d42-1838-42ba-a510-d8e0511cccec)

**Comment by Vinzent03** [comment]
The only option in the settings is the "open file without write in new pane". So not all open mode  can be specified.
