### ISSUE TITLE
URI to Random Note

### ISSUE THREAD

**Issue by RedHotUnicorn** [Vinzent03/obsidian-advanced-uri#22]
Would it be possible to add a URI for random note in a vault?
I have found mention the functionality in [command-uri-obsidian](https://github.com/deathau/command-uri-obsidian), but it is not working today , and repo abandoned.

**Comment by Vinzent03** [comment]
Do you want to open a random note in Obsidian via URI? Try this: `obsidian://advanced-uri?vault=<your-vault>&commandid=random-note`
