### ISSUE TITLE
Workspace parameter not opening workspace on Windows

### ISSUE THREAD

**Issue by sylumer** [Vinzent03/obsidian-advanced-uri#23]
Using the workspace parameter in an Obsidian URI to load a workspace works for me on Mac, but if I try the same URL on Windows, against the same vault, and with exactly the same workspace name set up, it does not work. When the URI is opened on Windows, the Obsidian app is opened, or is switched to the foreground, but no loading of the workspace takes place. When doing this on Mac, the workspace loads immediately .

- Other URI I have tried work on both platforms, and plugin is enabled on both.
- Restarting the Obsidian app made no difference.
- Remove and readded the plugin, but to no avail.

e.g. this URI works for me on Mac but not on Windows against the same vault and configuration.
```
obsidian://open?vault=demo&workspace=1-Main
```

---
**Windows:** 10 (21H1, build 19043.1165)
**Obsidian:** 0.12.15
**Advanced Obsidian URI Plugin:** 1.11.1

**Comment by Vinzent03** [comment]
I doubt that this URI works on your Mac. It's `obsidian://advanced-uri` and not `obsidian://open`

**Comment by sylumer** [comment]
Thanks for the prompt response. I will recheck it sounds **highly** plausible as an explanation 😖

I was going through some notes for setting up a few things that worked on my Mac, then followed them again on my PC. Entirely possible I've misread something and got differing URLs, so I will check and no doubt close the issue when I find this is indeed a user error on my part.

**Comment by sylumer** [comment]
Confirmed as user error. Closing.
