### ISSUE TITLE
Openening a note also reactivate the left pane to reveal the note

### ISSUE THREAD

**Issue by raphaelhuleux** [Vinzent03/obsidian-advanced-uri#24]
Hi, 

I'm using Obsidian Advanced URI with an Alfred workflow to open my notes directly from Alfred. When I activate the Advanced URI plug-in, opening a note also reactive the left panel and reveal where the note is located, which is a bit annoying. Any idea how to avoid that?

**Comment by Vinzent03** [comment]
Sorry, but I don't really understand what you mean. Could you share a video?

**Comment by chrisgrieser** [comment]
That was actually caused by my Alfred workflow, and not the Advanced URI plugin. See the [respective issue at my repo](https://github.com/chrisgrieser/shimmering-obsidian/issues/17).

Issue has been resolved on my side, so this issue can be checked off.
