### ISSUE TITLE
[Feature Request] Append/Prepend text to a specific note without opening Obsidian

### ISSUE THREAD

**Issue by FelipeRearden** [Vinzent03/obsidian-advanced-uri#25]
Hello again @Vinzent03 !!!!!!

I'd like to make a request related to these amazing URI:

`obsidian://advanced-uri?vault=<my_vault>&filepath=<my_file.md>&data=<my_data>&mode=prepend`

`obsidian://advanced-uri?vault=<my_vault>&filepath=<my_file.md>&data=<my_data>&mode=append`

**My suggestion is a new option to NOT open Obsidian while doing this URI.** 

**In other words: append/prepend text to a specific note without opening Obsidian (background)** 

## Why are you asking this?

Let me explain :)

- This week I started using Obsidian Mobile on iOS;
- I have a note in Obsidian called INP.md that I use to put everything that comes to my mind that I don't want to deal in the moment (TODO, reminders, links, short text ...)

My idea is to send (append/prepend) information to INP.md on Mobile using URI and the Shortcuts App. After searching in our [forum](https://forum.obsidian.md/t/ios-shortcuts-share-your-ideas/15149/28), I wrote two shortcuts that uses your amazing plug-in to append/prepend information to this INP.md note.

—> This one uses the clipboard to prepend to the note

![60A4AF6B-CA46-4D65-839E-2901301F8952](https://user-images.githubusercontent.com/85180696/135611179-08089c60-6e33-4851-b4db-dcef236e3b02.jpeg)

—> This one opens a modal that let me write what I want to remember and prepend to the note

![846E8723-22A3-45E2-A925-72134D0C9C7F](https://user-images.githubusercontent.com/85180696/135611202-39d0fe82-d2fd-4b26-9f32-431e3af05013.jpeg)
 

This is amazing, but every new input that I send via URI, Obsidian Opens and I have to get back to the previous App that I was using. 

Would be amazing to have a way to send information via URI on background (without opening Obsidian) :)

---

I hope my FR is feasible and I hope you liked :)

Thanks again for all your help. Is always a pleasure talking to you.

I wish you a fantastic day!!!!!!

**Comment by Vinzent03** [comment]
Closing for now, because (as discussed in Discord) Obsidian doesn't provide an API for that. But they might not be able to implement that too. Some workarounds were discussed in [Discord](https://discord.com/channels/686053708261228577/840286264964022302/893557230065049640)

**Comment by FelipeRearden** [comment]
100% agree @Vinzent03 !

Thank you very much for all your help. Lets hope that this could be a new feature in the future :)

**Comment by FelipeRearden** [comment]
⚠️Update about this Issue:

I found a way to do what is described here using an iOS App called ToolboxPro.

This post in our [Forum](https://forum.obsidian.md/t/ios-shortcuts-share-your-ideas/15149/78?u=felipe) explain what you need to do.

Have a great day!
