### ISSUE TITLE
open note OR reveal already open note

### ISSUE THREAD

**Issue by cedardocster** [Vinzent03/obsidian-advanced-uri#26]
Your plugin is super useful.  I use it to allow me to open files from a bash script (from a rofi search as well as other bash scripts e.g. from a crontab reminder type thing) as that's quicker than using the native Obsidian search.

The one slight wrinkle is that I get a lot of repeat notes all open at the same time.  Is there a way with your plugin (or any other way you know off the top of your head) to have it "go to" the already open note if it has been opened previously?

this is what I'm using to open my notes:
xdg-open "obsidian://advanced-uri?vault=${VAULT}&filename=${FILE}"

thanks,
- Dave

**Comment by Vinzent03** [comment]
Should be fixed in new [release](https://github.com/Vinzent03/obsidian-advanced-uri/releases/tag/1.11.2)

**Comment by cedardocster** [comment]
Awesome - thanks!!!
