### ISSUE TITLE
Feature Request: URI to open specific settings tabs

### ISSUE THREAD

**Issue by chrisgrieser** [Vinzent03/obsidian-advanced-uri#29]
Well, as I mentioned in Discord: A feature to open specific settings-tabs would be great. e.g. `obsidian://advanced-uri?settingid=editor` would open the editor settings and `obsidian://advanced-uri?settingid=hotkeys` would open the hotkeys.

**Comment by Vinzent03** [comment]
Available in new release!

**Comment by chrisgrieser** [comment]
wow, that was quick – thanks a lot 🙏

**Comment by chrisgrieser** [comment]
Quick Question: How do I determine the ID of a settings-tab? Can't find any mention of it in the readme.

**Comment by Vinzent03** [comment]
I found no list, but in my testing in was always the display name `editor`, `daily-notes`, `community-plugins`, ...

**Comment by YousufSSyed** [comment]
@Vinzent03 How can I make URIs to specific setting sections? I haven found any documentation on that.

**Comment by Vinzent03** [comment]
@YousufSSyed The documentation can be found here https://vinzent03.github.io/obsidian-advanced-uri/actions/settings_navigation

**Comment by YousufSSyed** [comment]
Thank you!
