### ISSUE TITLE
[BUG?] Cannot use # in data

### ISSUE THREAD

**Issue by Quorafind** [Vinzent03/obsidian-advanced-uri#3]
# WHAT

When I use # in data, the data would be null when obsidian recieve it.

like:

obsidian://advanced-uri?vault=MyBrain&filepath=_Inbox%2Fjournals%2F2021_04_02&data=##%20TODO%20test&mode=append

would send an object: 

![image](https://user-images.githubusercontent.com/13215013/113370219-dd787000-9395-11eb-8cb4-a7f26a1b0582.png)

# HOW

Don't know if it is a bug.

**Comment by Quorafind** [comment]
I find that I should use URL encoding for it.

**Comment by Vinzent03** [comment]
Yeah there is nothing I can do. URL encoding is needed.
