### ISSUE TITLE
X-Callback-URL and Shortcuts Actions

### ISSUE THREAD

**Issue by campjacob** [Vinzent03/obsidian-advanced-uri#30]
This plugin is excellent. I am using it with Obsidian for macOS and iOS through shortcuts mostly (although just having a link has been helpful in my task manager as well).

It does work to use the action [X-Callback-URL](https://support.apple.com/guide/shortcuts/use-x-callback-url-apdcd7f20a6f/ios), you can also see the [general spec page](http://x-callback-url.com). When I run that action, it just seems to just hang and not finish. Having the ability for these URLs to speak back to the application that sent them is a nice addition, especially if there is a sequence of steps. A workaround that currently works is to use the action "Open URL" and this will allow me to manipulate data in multiple different obsidan documents.

**Comment by Vinzent03** [comment]
So you want the plugin to support an `x-success` parameter, which should be called on success?

**Comment by campjacob** [comment]
I think it would make sense. That would allow apps including Shortcuts or Drafts to chain multiple URI[^1] calls to manipulate data in different pages as well to receive feedback from those calls that they were successfully completed. Do you know how most users end up launching the URIs from external apps? It might also include x-error, although I think you are handling that through a notification within Obsidian which might be the best way to manage it, but I again would argue that there are times that you might not even want to open obsidan. If I am calling one of the URIs from outside of the app, then I might want to stay in the app I am currently in (or return right to it)... but that only works if you know that it was successful or if there was an error.

[^1]: I'm not sure what the actual difference between URI and URLs is, but I just  mean whatever the link is that you can run different parameters

**Comment by Vinzent03** [comment]
Available in new release! I have no iOS device, so I cannot really test it. Let me know if you encounter any problems.
