### ISSUE TITLE
`search` and `searchregex` don't work with `daily=true`

### ISSUE THREAD

**Issue by Peeja** [Vinzent03/obsidian-advanced-uri#31]
Steps to reproduce:

* Put `abc` somewhere in the current daily note (in my case, `Periodic/Daily/2021-11-12`).
* Open `obsidian://advanced-uri?daily=true&search=abc&replace=123`.

**Expected:** The `abc` should be replaced with `123`.
**Actual:** Nothing changes.

---

Notably, as expected:

* `obsidian://advanced-uri?filepath=Periodic%252FDaily%252F2021-11-12.md` opens the file.
* `obsidian://advanced-uri?daily=true` also opens the file.
* `obsidian://advanced-uri?filepath=Periodic%252FDaily%252F2021-11-12.md&search=abc&replace=123` replaces `abc` with `123`.

**Comment by Vinzent03** [comment]
Sorry, but I can't reproduce. Are on version >=`1.13.0` ?

**Comment by Peeja** [comment]
Aw, geez, I forgot you don't see the Update buttons until you click the big Update All button first. 🤦🏻‍♀️ Just pulled in the update, and it works great. Sorry to take up your time! (Also, thanks for this plugin, it's _fantastic_.)
