### ISSUE TITLE
Minor Feature Request: URI to Open Plugin/Theme Browser + Update All

### ISSUE THREAD

**Issue by chrisgrieser** [Vinzent03/obsidian-advanced-uri#32]
I noticed after a while, that there are three things in the settings that I open very regularly, so speeding up the process via URI might be useful. In particular:
- trigger the "Update All Community Plugins" Function
- open the Community Theme Browser
- open the Community Plugin Browser

Right now, via the `settingid` URI, I can only access the community plugin tab, and the appearance tab, creating an unnecessary extra step. This is only a super minor feature request, so no hurry at all! :)

**Comment by Vinzent03** [comment]
(I just noticed my update all plugins action does not work, I try to fix it)

**Comment by Vinzent03** [comment]
Now it's hopefully really works. I have to wait 10 after checking for update, because the internal functions in Obsidian doesn't expose a Promise, so I don't know when it's finished with checking for updates.

**Comment by chrisgrieser** [comment]
Great, just tested it, works perfectly! 

However, what happens when the process of checking for updates takes longer than 10 seconds, e.g. because of many plugins/bad internet? 🤔

**Comment by chrisgrieser** [comment]
btw, the "updated all plugins" URI is not yet mentioned at all in the readme. (I got the URI by looking through the `main.ts`.)

**Comment by Vinzent03** [comment]
@chrisgrieser I know it's not a good solution, but the only way I could think of. It just presses the button again, so it can't break anything. I just won't work then. 

It's documented under [others](https://github.com/Vinzent03/obsidian-advanced-uri#others)
