### ISSUE TITLE
URI to save current workspace

### ISSUE THREAD

**Issue by chrisgrieser** [Vinzent03/obsidian-advanced-uri#33]
I see two methods of implementing this:
- A parameter like for example `save-current=true` to save a workspace before changing to a different workspace. 
- A separate URI for saving the current workspace, which can be run before the loading of a different workspace.

Not sure which implementation makes more sense, the latter is more fine grained control, while the former is more compact as it is only one URI.

**Comment by chrisgrieser** [comment]
Thanks a lot! Just to make sure I got this correctly:

`obsidian://advanced-uri?workspace=foobar&saveworkspace=true` will save the current workspace and then load the workspace "foobar", and

`obsidian://advanced-uri?saveworkspace=true` will simply save the current workspace?

**Comment by chrisgrieser** [comment]
Also minor thing: When only running `obsidian://advanced-uri?saveworkspace=true`, it does work as intended, however, there is no feedback to the user that anything happened (when not opening the console). I'd suggest to post a brief notification that the workspace has been saved.

**Comment by Vinzent03** [comment]
Oh yeah you are right. Will fix those two points.
