### ISSUE TITLE
Minor FR: URI to Add a folder as vault

### ISSUE THREAD

**Issue by chrisgrieser** [Vinzent03/obsidian-advanced-uri#35]
Basically, I am wondering whether it is possible to add a URI that adds a folder as a new vault, as would happen when you click this button.

<img src="https://user-images.githubusercontent.com/73286100/144707250-b99416a2-ccc7-4467-8c70-960a169a21f4.png" alt="image" width=60%>

The command could be sth like `obsidian://advanced-uri?open-as-vault={URI-encoded-folder-path}`?

**Comment by Vinzent03** [comment]
Sorry, but I couldn't find the method in the code, and it's a new window, so I cannot click on the buttons per code. The best I can offer is to call the command to open another vault and let the user press the button.

**Comment by chrisgrieser** [comment]
Hmmm, too bad. Thanks forgiving it a try!
