### ISSUE TITLE
[Feature Request] Add "Copy Advanced URI" to Hotkeys section (and Command Palette)

### ISSUE THREAD

**Issue by brump** [Vinzent03/obsidian-advanced-uri#37]
As far as I can tell, the "Copy Advanced URI" command is currently only available in the "More options" menu. It would be great, if we could invoke it with a quick keyboard shortcut instead of having to reach for the mouse, click on the the little "More options" menu button, and then click on the actual command inside that menu.

Thank you so much for this fantastic plugin. It's really filled to the brim with insanely useful features.

**Comment by Vinzent03** [comment]
It's already there. It's called `copy URI for file`

**Comment by brump** [comment]
Oh, now I see. I didn't realize `Copy Advanced URI` and `copy URI for file` actually invoke the same command. I thought `copy URI for file` always shows you that interactive dialog and `Copy Advanced URI` is context-aware (hence the "Advanced") and only shows you the dialog when it needs to, but apparently I just did not test `copy URI for file` carefully enough.

I think I was primed a bit to think they are different because of their different names, so I was not surprised that they (seemingly) behaved differently. Maybe renaming `Copy Advanced URI` to `Advanced URI: Copy URI` would reduce the chance of someone else being confused by this.

Anyway, thanks again for all your great work!
