### ISSUE TITLE
how to specify preview mode?

### ISSUE THREAD

**Issue by zeltak** [Vinzent03/obsidian-advanced-uri#38]
Hi all

im trying to create a complex (well at least to me since im suck :) ) obsidian advanced URL to launch from within ios shortcuts.

this is the current state of what works

```
obsidian://advanced-uri?vault=Food&filepath=CQ/title&data=body
```

this does create a note with `title` and a body `body` which is great. but it always opens in reading mode

I've read that you can use `view` mode to specify the mode it will open in. yet for the life of me i cannot get it to work or follow the correct syntax for this

can anyone guide me

also can one launch a insert template after the advanced URI launches?

thx so much

Z

**Comment by zeltak** [comment]
ok after many trial and error found it!
for anyone interested here is is

```
obsidian://advanced-uri?vault=Food&filepath=CQ/title&viewmode=source&data=body
```

**Comment by Vinzent03** [comment]
What was your problem? What uris didn't work out?

**Comment by zeltak** [comment]
thx @Vinzent03!

the issue was i wasn't aware of the correct syntax to use :D since there were no examples on the main README.

if you want i will gladly add additional examples if you want in a wiki/other

best

Z

**Comment by Vinzent03** [comment]
As stated at the top of the readme it's always `obsidian://advanced-uri?vault=<your-vault>&<parameter>=<value>&<parameter2>=<value2>`. As stated in the [readme](https://github.com/Vinzent03/obsidian-advanced-uri#view-mode) is `viewmode` the parameter and `source`/`preview` the value. So you can append it to your existing uri with `&viewmode=source`
