### ISSUE TITLE
`line in file` command seems to not work?

### ISSUE THREAD

**Issue by zeltak** [Vinzent03/obsidian-advanced-uri#39]
Hi again

This is similar to my previous issues where i may be doing something wrong but i cant see any examples :)

to my understanding the `line in file` command should open the note with the cursor on the line #? is that correct?

if so i have this example

```
obsidian://advanced-uri?vault=Food&filepath=CQ/test&viewmode=source&data=XXX%0D%0A333&line=2

```

which creates the test file but never moves the cursor to line #2

any tips?

thx

Z

**Comment by Vinzent03** [comment]
What does the created file look like? Is the 333 in a new line? With a different encoding I can reproduce the issue.

`XXX%250A333` as data

**Comment by zeltak** [comment]
thx again!

the above was an example i just created to see if i can get it to work and get the cursor to show on the 2nd line (hence the `line=2`) in the command. this hasent worked with this example or any other examples where i parse encoded text in the `data=` command.

what im trying to do is use `advance uri` with siri shortcuts to create a new note and have the cursor positioned in the `YAML frontmatter` tag section ie:

```
---
tags: 
- CURSOR GOES HERE
```

![image](https://user-images.githubusercontent.com/498410/147970220-7430da69-1d01-4187-8849-eb3577a68227.png)


is that possible at all?

thx so much

Z

**Comment by Vinzent03** [comment]
Yeah it should be possible. Will have to fix it in the next days.

**Comment by Vinzent03** [comment]
Should be fixed now. But by the way, it was only listed under `Navigation` and not under `Writing` so the documentation didn't say it would work for writing too. (Although it should support it)

**Comment by zeltak** [comment]
perfect thx so much!!!

Z
