### ISSUE TITLE
Copy advanced-uri to clipboard

### ISSUE THREAD

**Issue by Connor-yang96** [Vinzent03/obsidian-advanced-uri#4]
no any option, no any shortcuts. 

obsidian://advanced-uri?vault=vaultName&file=Test%2F2

---
I found the uri is diff : `obsidian://advanced-uri?vault= ` vs `obsidian://open?vault=`

Why not add option in `obsidian://open?vault=<your-vault>&filepath=my-file&heading=Goal`  ???

**Comment by Vinzent03** [comment]
This is a restriction of the Obsidian api. Another so called `action` (like `open` and `search`) is needed. But adding somehow the option to copy an adcanced-uri URI is a good idea.

**Comment by Connor-yang96** [comment]
Okay. That's the restriction of ob's api. Hope they will open this . 

Directly heading and block by ob's uri is really useful . 

Yeah. shortcut to copy uri is really indeed. 

Thank you .
