### ISSUE TITLE
URI Fails to complete

### ISSUE THREAD

**Issue by gmakstutis** [Vinzent03/obsidian-advanced-uri#41]
I'm using an iOS Shortcut to create a URI to generate a page. This includes dataviewjs blocks. The process of generating the page fails at the same point, but I cannot understand why.

This is the URI:

`obsidian://advanced-uri?vault=PPTN&filepath=More%20Testing/More%20Testing%20Dashboard&data=---%0Atype:%20project%0Aproject-start:%202022-01-13%0Aproject-due:%20%0Aarea:%0Atags:%20%5B%5D%0A---%0A%0A%5B%20%5B%5BMain%20Dashboard%7C%F0%9F%97%84%EF%B8%8F%5D%5D%20-%20%5B%5BMore%20Testing%20Dashboard%20%7C%F0%9F%93%81%5D%5D%20-%20%7C%7C%20%5B%F0%9F%93%8A%5D(obsidian://advanced-uri%3Fvault%3DPPTN%26workspace%3DGraphs)%20-%20%5B%F0%9F%93%B1%5D(obsidian://advanced-uri%3Fvault%3DPPTN%26workspace%3DMobile)%20%5D%0A%5Eheader-links%0A%0A---%0A%0A%23%20Project%20Info%0A%0A%3E%20%23%23%20More%20Testing%0A%3E%20%23%23%20Start:%20%60%3Dthis.project-start%60%0A%3E%20%23%23%20Due:%20%60%3Dthis.project-due%60%0A%0A---%0A%0A%23%20Tasks%0A%0A!%5B%5BButtons%23%5EmakeTask%5D%5D%0A%0A%60%60%60dataviewjs%0A%09dv.taskList(dv.pages('%22More%20Testing/001-Tasks%22').file.tasks.where(t%20%3D%3E%20!t.completed).sort(f%20%3D%3E%20f.due),%20false%20)%0A%60%60%60%0A%0A---%0A%0A%23%20Notes%0A%0A!%5B%5BButtons%23%5EaddNote%5D%5D%0A%0A%60%60%60dataview%0Alist%20from%20%22More%20Testing/002-Notes%22%0A%60%60%60%0A---%0A%0A%23%20Resources%20%0A%0A!%5B%5BButtons%23%5EmakeResource%5D%5D%0A%0A%60%60%60dataview%0Alist%20from%20%22More%20Testing/003-Resources%22%0A%60%60%60%0A%0A---%0A%5B%20%5B%5BMain%20Dashboard%7C%F0%9F%97%84%EF%B8%8F%5D%5D%20-%20%5B%5BMore%20Testing%20%7C%F0%9F%93%81%5D%5D%20%5D%0A%5Efooter-links`

And it should generate this Markdown:

`
---
type: project
project-start: 2022-01-13
project-due: 
area: employment
tags: [jobs]
---

[ [[Main Dashboard|🗄️]] - [[LSB Technical College Dashboard |📁]] - || [📊](obsidian://advanced-uri?vault=PARA&workspace=Graphs) - [📱](obsidian://advanced-uri?vault=PARA&workspace=Mobile) ]
^header-links

---

# Project Info
> ## LSB Technical College
> ## Start: `=this.project-start`
> ## Due: `=this.project-due`

---
# Tasks
![[Buttons#^makeTask]]

```dataviewjs
	dv.taskList(dv.pages('"LSB Technical College/001-Tasks"').file.tasks
	.where(t => !t.completed)
	.sort(f => f.due),false)
```
---
# Notes 
![[Buttons#^addNote]]

```dataview
list from "LSB Technical College/002-Notes"
```
___
# Resources 
![[Buttons#^makeResource]]

```dataview
list from "LSB Technical College/003-Resources"
```

---
[ [[Main Dashboard|🗄️]] - [[LSB Technical College Dashboard |📁]] ]
^footer-links
`

The point where it fails is: 
`
dataviewjs
	dv.taskList(dv.pages('"LSB Technical College/001-Tasks"').file.tasks
	.where(t => !t.completed)
	.sort(f => f.due),false
`

Essentially, after 'false', the process of creating the content in Obsidian stops.

Any idea what is causing this?

Many thanks

**Comment by Vinzent03** [comment]
Hey sorry for late reply. Does the issue still persist. I would try to help then.

**Comment by gmakstutis** [comment]
No problem. I can't confirm whether it is still an issue, as I found a work-around. If it reappears, I'll get in touch. Thanks
