### ISSUE TITLE
Item Author Missing in Plugin list

### ISSUE THREAD

**Issue by chrisgrieser** [Vinzent03/obsidian-advanced-uri#44]
just a minor thing, but since since this is such a wonderful plugin, I think you deserve to have your name there as with all the other plugins

<img width="1082" alt="Screenshot 2022-02-02 16 46 54" src="https://user-images.githubusercontent.com/73286100/152188527-3109a25d-c6fa-4ab6-92b3-22b235828d5d.png">

**Comment by Vinzent03** [comment]
Thx for the hint. Appreciate you take care of my "publicity" :joy:
