### ISSUE TITLE
Append to heading dont work on the last heading

### ISSUE THREAD

**Issue by simzdk** [Vinzent03/obsidian-advanced-uri#45]
When I try to append to the last heading of a page and have a trailing comment, the last heading append, dont work. 
![202202 - Obsidian - 2022-02-23 at 13 44 20](https://user-images.githubusercontent.com/155539/155321836-79a6c806-892d-42cf-8615-6338268593ba.png)

Syntax used: 
`obsidian://advanced-uri?vault=MyVault&uid=testingpage&heading=Heading1&data=Heading1Test&mode=append`

**Comment by Vinzent03** [comment]
Sorry, but what exactly doesn't work? Where do you expect `Heading3Test` to land?

**Comment by simzdk** [comment]
> Sorry, but what exactly doesn't work? Where do you expect `Heading3Test` to land?

I realized, it work as expected, but I would like 'Heading3Test' to land just under 'Heading 3'. So if you have a bunch of trailing comments below headings, its still possible to inject text in the last heading.
