### ISSUE TITLE
Better integration with Hook

### ISSUE THREAD

**Issue by wenlzhang** [Vinzent03/obsidian-advanced-uri#46]
Is it possible to support smoother integration with Hook as discussed in the following post?
https://discourse.hookproductivity.com/t/link-obsidian-with-advanceduri-plugin/4691/6

> Hook is not able to get the advanced URI. Currently, it seems it is impossible to set a shortcut for just copying advanced URI without bringing up the UI. Besides it would be better to have proper automation without UI scripting
> 
> If the advanced URI plugin provide the following two we could provide integration:

> “copy advanced markdown URI” for both title and url.
> Allow the user to set a shortcut for “copy advanced markdown URI” without bringing up the UI so Hook can use the shortcut to > get the markdown URI.

> However, much better would be to provide x-callback-url support in the plugin. Or other automation. Is that there or possible?

**Comment by Vinzent03** [comment]
(Discussing on their forum currently)
