### ISSUE TITLE
How to open a file in a new page instead of the current page?

### ISSUE THREAD

**Issue by ShiTieSeng** [Vinzent03/obsidian-advanced-uri#50]
How should I modify this uri to achieve it?

`obsidian://advanced-uri?vault=<your-vault>&filepath=my-file`

**Comment by Vinzent03** [comment]
There is currently only a setting in the plugin's settings, which would be applied to all uri opening a file. Will add support for an uri parameter today.

**Comment by Vinzent03** [comment]
See [here for documentation](https://vinzent03.github.io/obsidian-advanced-uri/concepts/navigation_parameters#new-pane)

**Comment by ShiTieSeng** [comment]
So fast, Cool!
