### ISSUE TITLE
[feature request]: support text fragment

### ISSUE THREAD

**Issue by windily-cloud** [Vinzent03/obsidian-advanced-uri#52]
The [scroll to text fragment](https://wicg.github.io/scroll-to-text-fragment/) feature provides support for specifying a text snippet in the URL hash. So if I click a link that specifies a fragment, I would be navigated to that fragment of text on the page.

if obsidian-advanced-uri support it , I guess I can link any character from any document. This is more elegant than the obsidian block reference.

Some links to understand text fragment:
- https://mgearon.com/html/text-fragments/
- https://wicg.github.io/scroll-to-text-fragment/#generating-text-fragment-directives
- https://github.com/GoogleChromeLabs/link-to-text-fragment/blob/main/fragment-generation-utils.js

Thank you for any replies.

**Comment by promisenever** [comment]
我也有类似的想法，如果可以支持直接链接某一个标题下，或者段落，那会扩展很多可能性。

**Comment by Vinzent03** [comment]
@promisenever This is an english plugin so please use English so everyone can understand you.

It's already possible to navigate to headings or block references. It's documented [here](https://vinzent03.github.io/obsidian-advanced-uri/actions/navigation)

**Comment by windily-cloud** [comment]
Although this is very different from my expectations, I have thought about it carefully and indeed the current solution is the most elegant one. Thanks for the reply and for building such a great plugin!
