### ISSUE TITLE
"Open" action got stuck for several seconds sometimes

### ISSUE THREAD

**Issue by laphylee** [Vinzent03/obsidian-advanced-uri#53]
Thank you for the great plugin! I use this plugin a lot. There is an issue that has been bothering me for a long time. The "Open" action got stuck for several seconds sometimes, before opening the target page. It doesn't happen every time. There is no error message in the DevTool console. 
What could be the reason? Or How could I debug this issue?

**Comment by Vinzent03** [comment]
Could you share an example uri?

**Comment by laphylee** [comment]
obsidian://open?vault=Logseq&file=pages%2FScratch

**Comment by Vinzent03** [comment]
That's a default Obsidian URI and not from this plugin. https://help.obsidian.md/Advanced+topics/Using+obsidian+URI
