### ISSUE TITLE
Add UID failed when front matter contains colon ':'

### ISSUE THREAD

**Issue by EvanLind** [Vinzent03/obsidian-advanced-uri#54]
**Describe the bug**
Add UID failed when front matter contains colon ':'
And after manual modification，uri jump doesn't work

**To Reproduce**
1. Front matter like: 
```markdown
---
title: Convex Decomposition: xxx
---
```
2. Command palette call `copy URI for file`
3. Front matter change to: 
```markdown
---
id: d8e19562-62ca-49aa-9494-e817ebbe5c53
---
---
title: Convex Decomposition: xxx
---
```

**Desktop**
 - OS: Arch Linux
 - Obsidian Version: v0.14.5
 - Advanced Obsidian URI: 1.21.1

**Comment by Vinzent03** [comment]
That's because that's not valid `yaml`. The "language" or syntax of the frontmatter is `yaml`, which doesn't allow a space after `:`. You can check your frontmatter between the `---` [here](https://yamlchecker.com/)

**Comment by Vinzent03** [comment]
The easiest solution is to wrap you value in `"`:
```yaml
---
title: "Convex Decomposition: xxx"
---
```

**Comment by EvanLind** [comment]
I got it, thanks!
