### ISSUE TITLE
[bug?] Copy open file url haven't according to UID field in frontmatter.

### ISSUE THREAD

**Issue by YIRU69** [Vinzent03/obsidian-advanced-uri#55]
- setting
![image](https://user-images.githubusercontent.com/48148292/163662918-9fa5921c-aa0e-44af-8ab7-ff82466119bc.png)
- yaml id
![image](https://user-images.githubusercontent.com/48148292/163662937-e7439f50-e34b-466d-afdf-5c4cb341cc22.png)
- open file link 
obsidian://advanced-uri?vault=Mybase&uid=20220405202039390

Why are there different number?

**Comment by Vinzent03** [comment]
Could you please give some more reproduce steps? I guess you first set the id in the frontmatter and then called the command to get the corresponding uri?

**Comment by YIRU69** [comment]
Right, first set the id and get the uri.

**Comment by Vinzent03** [comment]
Seems the issue lies in Obsidian itself. The parsed frontmatter is wrong. You can solve this by wrapping the value in `"` or `'` to make it a String. I think the issue lies in some number limit.

**Comment by YIRU69** [comment]
Thanks.
