### ISSUE TITLE
can `plugin-browser` page auto focus the search element?

### ISSUE THREAD

**Issue by hyaray** [Vinzent03/obsidian-advanced-uri#56]
is this a good idea? what do you think??😁

**Comment by Vinzent03** [comment]
I wish Obsidian would do it by default. I don't find a way to access the modal so I don't know how to focus the search field. You can like this [feature request](https://forum.obsidian.md/t/minor-automatic-focus-on-community-plugin-search-in-settings/34666).

**Comment by hyaray** [comment]
I wish too. Thanks for your sharing.
BTW, how to find `settingid`, I don't find it in docs.😂
Best Regards!!

**Comment by hyaray** [comment]
I tried and show them [here](https://forum-zh.obsidian.md/t/topic/7365), FYI

**Comment by Vinzent03** [comment]
Thanks, done.

**Comment by Vinzent03** [comment]
I'm not planning on fixing it in this plugin. It should be fixed by Obsidian itself.
