### ISSUE TITLE
[Feature Request] Add Copy URI for Current File

### ISSUE THREAD

**Issue by joelberger76** [Vinzent03/obsidian-advanced-uri#57]
`Advanced URI: copy URI for file` works great, but the modal creates friction when I often just want a uid-based link to the current file. I would love to see a new command (or setting) that skips the modal and provides an Advanced URI to the current file, similar to how it works already for heading/block references.

Presumably, this would also work for the context menu option `Copy Advanced URI` since they appear to function the same.

**Comment by Vinzent03** [comment]
I see your problem. Will add that soon.

**Comment by joelberger76** [comment]
This is great, thank you! Any chance you could offer it without the file selection modal (just assume current file)?
