### ISSUE TITLE
Could this feasibly support uploading images?

### ISSUE THREAD

**Issue by SimplGy** [Vinzent03/obsidian-advanced-uri#58]
Use case would be to speed up an image import / note taking process [like this one](https://www.reddit.com/r/ObsidianMD/comments/rcgtpc/faster_method_to_embed_images_in_a_note_ios/)

iOS shortcuts could feasibly use this to make a whole image based capture workflow really efficient:

* (ios-shortcut) capture the most recent image
* (ios-shortcut) get text from that image
* (ios-shortcut) base64 encode the image
* upload that image to the vault with `obsidian://advanced-uri?vault=<your-vault>&filepath=my-file.png&data=${base_64}`
* (ios-shortcut) create a markdown snippet like `![TEXT_FROM_IMAGE.slice(0,32)](PATH_TO_IMAGE)`
* append that snippet to a daily note with `obsidian://advanced-uri?vault=<your-vault>&filepath=my-file.md&data=${TEXT}&mode=append`

**Comment by Vinzent03** [comment]
I have huge problems testing this, because the base64 data of a test image is 800000 character long. I don't even know if Obsidian can handle such long uri.

**Comment by SimplGy** [comment]
It's kind of a crazy idea, I grant you. I have been using it though -- ios shortcuts let you resize an image, and also convert it to base64 data, so it works just fine to embed that into a note if the size is <300px (think: thumbnails, not high-res).

Limit on url length is pretty long these days, the bigger practical impact is that edit view of your notes is a mess if there's too much base64 in there.

Would be much better if there were a way to put an image into the vault and reference that local vault image "url", but I haven't gotten there yet.
