### ISSUE TITLE
Shorthand for common usages

### ISSUE THREAD

**Issue by NomarCub** [Vinzent03/obsidian-advanced-uri#59]
[Built in URLs](https://github.com/obsidianmd/obsidian-docs/blob/master/en/Advanced%20topics/Using%20obsidian%20URI.md#shorthand-formats) have some shorthands for common uses that omit `?` and query strings. They would be convenient here too.

For example I can imagine writing `obsidian://advanced-uri/your-vault/my-file/Goal` instead of `obsidian://advanced-uri?vault=your-vault&filepath=my-file&heading=Goal`.

**Comment by Vinzent03** [comment]
I think you are one of the top issue authors at my plugins. 😂
I really like the idea. I don't know if that's achievable with the available plugin API, but I will try when my vacation ends.

**Comment by NomarCub** [comment]
I must've gotten good at wanting new features 😄
Thanks for the consideration, it's not critical by any means. Have a nice vacation!

**Comment by Vinzent03** [comment]
If I rember correctly, the most of them were bugs with Obsidian Git, but sure let's call them feature requests... 😂
Thanks

**Comment by Vinzent03** [comment]
I tried it, but it looks like Obsidian doesn't support this. The scheme is `obsidian://<action>?<query-parameters>`. `action` needs to be specified by the plugin, but since it's variable if you pass the file name, it's currently not possible. At least, I don't know a way currently.

**Comment by Vinzent03** [comment]
I'm closing this now, as I see no way to implement it.
