### ISSUE TITLE
Open note without opening a new pane?

### ISSUE THREAD

**Issue by luckman212** [Vinzent03/obsidian-advanced-uri#6]
Hi @Vinzent03 - great plugin!

I am using it to open my daily note, with e.g. `obsidian://advanced-uri?vault=main&daily=true`

It works, but always opens a new pane instead of just switching my current pane to the daily note (which is what Obsidian's native URI open does). Is there any way to fix or control this? Even if I have the daily note open, it still opens a new pane.

**Comment by Vinzent03** [comment]
I have currently bind it to the setting to open a new pane on write. But you are right an extra settings would be better.

**Comment by luckman212** [comment]
Hmm, I just noticed you have this toggle...

![image](https://user-images.githubusercontent.com/1992842/113964910-70803280-97fa-11eb-9356-1ec631c449a8.png)

When did you add that? It works to solve this issue

**Comment by Vinzent03** [comment]
Yeah like I mention its currently bound to this setting. But that's nonsense. (This setting was added at the first release)
