### ISSUE TITLE
"multi same name heading" support

### ISSUE THREAD

**Issue by OriginalSinCat** [Vinzent03/obsidian-advanced-uri#65]
**Situation：**
markdown file like following:

```
# heading1
balablabla...
balablabla...
balablabla...
balablabla...
balablabla...
balablabla...
balablabla...balablabla...

## myheading
balablabla...
balablabla...

# heading2
balablabla...
balablabla...

## heading2-1
balablabla...

### myheading
balablabla...
balablabla...


# heading3
balablabla...
balablabla...


## myheading
balablabla...
balablabla...


```

**Operation:**
access url=obsidian://advanced-uri?vault=vault&file=filename&heading=heading2#myheading
since there are two heading name is "myhead"，I split sub heading with `#` and want to locate the second "myheading"

**Except result:**
open file and locate to "myheading" of "heading2" under "heading2-1" level

**Real result:**
open file and locate to heading2. 

please add feature to support locate sub heading when there contains same heading name in markdown file

**Comment by Vinzent03** [comment]
I'm currently using Obsidian's default heading navigation `[[file#heading]]`, which doesn't support this. I see the problem and will see what I can do. Probably not that easy.

**Comment by OriginalSinCat** [comment]
Year, I see :). I tested `[[file#heading]]` , it seems maybe a lack feature of Obsidian, not the problem of advanced-uri.
I should post this problem to Obsidian offcial community.
Thanks for your reply 👍

**Comment by OriginalSinCat** [comment]
Year, I see :). I tested [[file#heading]] , it seems maybe a lack feature of Obsidian, not the problem of advanced-uri.
I should post this problem to Obsidian offcial community.
Thanks for your reply 👍
