### ISSUE TITLE
FR: URI to Disable/Enable Plugins

### ISSUE THREAD

**Issue by chrisgrieser** [Vinzent03/obsidian-advanced-uri#66]
For automation purposes, I'd also like to enable and disable plugins. I could see something like this:

```url
obsidian://advanced-uri?enable-plugin=<plugin-id>
obsidian://advanced-uri?disable-plugin=<plugin-id>
```

**Comment by Vinzent03** [comment]
Available in new release 1.25.0

**Comment by chrisgrieser** [comment]
woah, that was quick. Thanks <3

**Comment by chrisgrieser** [comment]
Hey, I finally found the time to implement the respective feature in my Alfred workflow.

However, it seems there is some bug with it, when I open the URI, nothing happens, the plugin stays enabled, and the console only logs this:

<img width="685" alt="Pasted image 2022-08-28 11 16 52" src="https://user-images.githubusercontent.com/73286100/187066898-ae65c4dd-6c00-470c-a092-8bdaf1158351.png">

**Comment by chrisgrieser** [comment]
oh, I am just notice that the last release is from July, meaning the feature isn't shipped yet 🙈

**Comment by Vinzent03** [comment]
Probably won't be able to release a new version until next week. Sorry for taking so long.

**Comment by chrisgrieser** [comment]
no worries!

**Comment by Vinzent03** [comment]
I don't know what the cause for the infinite GitHub action was, but the release is now out!
