### ISSUE TITLE
BUG: I have meet a fatal problem for me!

### ISSUE THREAD

**Issue by YIRU69** [Vinzent03/obsidian-advanced-uri#67]
Hi, @Vinzent03
I always use your plugin. Until I meet a fatal problem for me today. 
These step what I do.
1. set the file yaml
```
id: '20220728194221835'
tags: 'tag1', tag2 
```
2. open menu and open `Advanced URI: copy URI for current file`
3. then I can't get my advanced url what I want, like `obsidian://advanced-uri?vault=Mybase&uid=20220728194221835`. It is `obsidian://advanced-uri?vault=Mybase&uid=52195e59-d1c1-421e-953a-ec6833a5e0bb`
4. I test so many times  and find the problem `tags: 'tag1', tag2 `, it cause it. Why? I don't understand. If I set `tags: tag1, tag2 `, I can get the advanced url what I want. Is it normal?

**Comment by Vinzent03** [comment]
Your YAML is not valid.
Either 
```yaml
id: '20220728194221835'
tags: ['tag1',tag2] 
```
or 
```yaml
id: '20220728194221835'
tags:
    - 'tag1'
    - tag2 
```
See [yaml documentation](https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html)

**Comment by YIRU69** [comment]
yeah, I know what you mean. I just have a question that make sure if the yaml miss formate can cause the plugin error.

**Comment by Vinzent03** [comment]
If the yaml is wrong, it can't correctly read the value of `id`. When switching to reading mode in Obsidian, it should show you that the yaml is wrong too.

**Comment by YIRU69** [comment]
Thank you!
