### ISSUE TITLE
Is there a way to read a front-matter key?

### ISSUE THREAD

**Issue by phillipjohnston** [Vinzent03/obsidian-advanced-uri#68]
Hello,

First - thanks for the work on this plugin, I leverage it in a number of automated workflows.

Is it possible to read a front matter key from a given file and copy it to the clipboard?

**Comment by Vinzent03** [comment]
Available in new release: https://vinzent03.github.io/obsidian-advanced-uri/actions/miscellaneous#read-frontmatter

**Comment by phillipjohnston** [comment]
Thank you!

**Comment by saikarthikp9** [comment]
@Vinzent03 How to write to frontmatter? Specifically looking to just increase value by 1. Thanks.
