### ISSUE TITLE
Add URI builder for daily notes

### ISSUE THREAD

**Issue by Quorafind** [Vinzent03/obsidian-advanced-uri#7]
# HOW

Using a link like: ` obsidian://advanced-uri?vault=MyDaily&daily=true&data=%3C%25%20tp.file.cursor%20%25%3E&mode=append` 

And the append action fails with no data append to the daily note.

Is it a bug for Obsidian or just a bug for the plugin?

**Comment by Vinzent03** [comment]
How do you open the link? Can you try to click on it in **preview** in Obsidian?

**Comment by Quorafind** [comment]
@Vinzent03 I did open the link on mobile

**Comment by Quorafind** [comment]
And if I click the link on Obsidian desktop, it shows a message like this :

![image](https://user-images.githubusercontent.com/13215013/114001305-63ad1e80-988e-11eb-83f3-8576bdef137e.png)

**Comment by Vinzent03** [comment]
How did you create that URI? Could you please update to the latest version and use the `Copy URI for current file` command to get the encoded data string. Then you can take the data part and put it into your daily URI.

**Comment by Vinzent03** [comment]
Oh if I try to decode it. I see its already valid. I guess you already used such tool. Will take a look, why it's still not valid

**Comment by Quorafind** [comment]
I have tried the newest version of this plugin in a blank vault, but it is still not work as I want. 

And what I want to insert is `<% tp.file.cursor %>`

**Comment by Vinzent03** [comment]
I was wrong and my plugin works. Only some validator I tried was wrong. When you call the command and you are not in a heading or block reference a suggest model opens. There you can insert your data. The built URI is copied to your clipboard. Then you can replace `filepath=...` with `daily=true`. 

It should result in: 
`obsidian://advanced-uri?vault=MyDaily&daily=true&data=%253C%2525%2520tp.file.cursor%2520%2525%253E&mode=append`

Will add an URI builder for the daily note too.

**Comment by Quorafind** [comment]
It works! I used URL Encode Online to encode my data, so I used `%25` to send `%`. Sorry

**Comment by Vinzent03** [comment]
That's correct, but (I don't know why) `%25` needs to be encoded again. xD
