### ISSUE TITLE
Support navigating to specific elements, areas and groups in Excalidraw drawings

### ISSUE THREAD

**Issue by wenlzhang** [Vinzent03/obsidian-advanced-uri#70]
It would be great if one can go to specific elements, areas and groups in Excalidraw drawings from external apps.

For an internal Obsidian link, one can use the following linking syntax for the three purposes above:

- [[file#^elementID]]
  - This one has the same syntax as ordinary block links.
- [[file#area=Section heading]]
  - This one has the prefix "area".
- [[file#^group=elementID]]
  - This one has the prefix "group".

More details can be found on the following page:

https://github.com/zsviczian/obsidian-excalidraw-plugin

Therefore, it would be great if one can achieve something similar with Advanced URI so that such linking syntaxes would also work from external apps.

**Comment by Vinzent03** [comment]
Sorry for **late** reply. I'm currently going through open issues.
This should already be possible by using the existing heading parameter. You should be able to pass `area=Section heading` as value. For element id use the block reference parameter.
