### ISSUE TITLE
Open URI in new window

### ISSUE THREAD

**Issue by Rhydderch** [Vinzent03/obsidian-advanced-uri#74]
Hello,

I am using your plugin to open specific workspaces/
Do you think it would be possible to add an argument to the URI that would open a workspace (from the same vault) in a new window? (so that I can have two workspaces of the same vault open at the same time? Or is this not possible due to obsidian limitations?)

Best,
Rhydderch

**Comment by Vinzent03** [comment]
I don't think workspaces work that way. They save the window configuration as well. So it's not possible to load a workspace in a specific window. Or am I missing something?

**Comment by Vinzent03** [comment]
Closing because of no response. Just comment if you have still problems, and I'm open to reopen the issue.
