### ISSUE TITLE
[Feature Request] Pass additional context in URL

### ISSUE THREAD

**Issue by panahi** [Vinzent03/obsidian-advanced-uri#77]
**Use Case**
I'm starting to build a number of automations that leverage obsidian-advanced-uri to invoke commands (some external to obsidian, like via shortcuts, and some internal from buttons in dataview output). 

For something like what I'm trying to do in https://github.com/Vinzent03/obsidian-advanced-uri/issues/76, the flow ends up like:
- click on button in a dataview table listing out tasks
- button uses advanced-uri to navigate to the file that contains the task and puts the cursor on the line that contains the task and then executes a quickadd macro
- the quickadd macro puts the currently active line into my clipboard, and then executes javascript which pulls the content out of my clipboard.

My ultimate goal is to not have to navigate to the other file itself. I think this is possible if advanced-uri were enhanced like:
- expose an API object or something (like how buttons and metaedit do) that a script can access via `app.plugins.plugins['obsidian-advanced-uri`]
- That API object can expose the query parameters of the most recent URI invoked

This way, I could pass extra params like &taskfile=<filename>&taskline=<linenumber> and access them without the weird clipboard nonsense. I have both of those values at the time of creating my dataview table.

**Comment by Vinzent03** [comment]
The plugin is already available like all other plugins via `app.plugins.plugins['obsidian-advanced-uri]`. How would the api object be different from the current available methods?

Storing the last query parameters is an easy fix.

**Comment by panahi** [comment]
@Vinzent03 Sorry, I meant that while the plugin is accessible there isn't any (that I can see) fields exposed from the object that might contain information like the last query parameters. But that's a moot point I guess - adding a way to get the last query parameters is enough for me

**Comment by Vinzent03** [comment]
Does the new version help you? You can access via `app.plugins.plugins["obsidian-advanced-uri"].lastParameters`

**Comment by panahi** [comment]
That's awesome, thanks for the update. I'll try it out this weekend!

**Comment by panahi** [comment]
Works great! I was able to change some workflows so that I don't need to change the active file or track state in the clipboard :). And my quick add macro could drop this nonsense and just run the user script

![image](https://user-images.githubusercontent.com/1176656/193425566-a6dbd747-6128-4535-9e58-4d406a1178a5.png)

**Comment by hihihlo** [comment]
@Vinzent03 May I suggest to add the info into document ?
I had a similar problem today, and found the post accident.
This is a powerful feature !

**Comment by Vinzent03** [comment]
Good idea! Done.
