### ISSUE TITLE
[Feature Request] URI to open note in popover mode

### ISSUE THREAD

**Issue by daxmonson** [Vinzent03/obsidian-advanced-uri#79]
While inline in one note, it would be helpful to be able to use an advanced URI to call up another note via IOS shortcut by voice etc so that it pops up over the top of current note. This way you could stay in the flow of the original note and not have to do a bunch of navigating.

**Comment by Vinzent03** [comment]
Does obsidian have such popover mode? So do you want me to open a file in a popover or to craft the popover mode itself as well?

**Comment by daxmonson** [comment]
Yep, it's the page preview in the core plugins, triggered by cmd and hovering the cursor over a link. I think if there was a way to call up a note to display this way via URI there wouldn't be a need to craft it. If possible, it would be a very welcomed addition. Thanks for considering it.

**Comment by XMB-7** [comment]
There is a plugin called Hover Editor that provides such a popover mode feature, but not sure if it is easy to collaborate with it.
BTW, highly recommended trying Hover Editor, it is the one could enhance people's workflow.

**Comment by Vinzent03** [comment]
Available via the new [openmode](https://vinzent03.github.io/obsidian-advanced-uri/concepts/navigation_parameters#open-mode) parameter

**Comment by daxmonson** [comment]
Thanks for implementing this, I just bought you a coffee. 

I've got a vault "Ipad" and a note "say something" which I'm able to call up and open with an advanced URI. I've looked at the schema for popups and have tried to use different syntax to pull it up in popover, but haven't been able to yet (have hover editor installed). Maybe time for me to go by myself a coffee. 

obsidian://advanced-uri?vault=IPad%20Vault&filepath=Say%2520something=openmode=popover.md

Possible to write the line correctly in advanced URI schema? Thanks

**Comment by Vinzent03** [comment]
Thank you! The `.md` corresponds to the `filepath` parameter and not to the end.

**Comment by XMB-7** [comment]
I guess the correct one is `obsidian://advanced-uri?vault=Ipad&filepath=say%20something&openmode=popover`.

**Comment by Vinzent03** [comment]
@daxmonson Oh I'm sorry I just found a bug in the implementation. Fixed in 1.29.2.
