### ISSUE TITLE
Would you like to add more parameters for Execute command?

### ISSUE THREAD

**Issue by Shuusei04** [Vinzent03/obsidian-advanced-uri#8]
Hi, I hope to insert my template in append mode for my daily notes. But I couldn't implement such things by using current parameters. Would you like to add some parameters to Implement such functionality? Thank you!

**Comment by Vinzent03** [comment]
So instead of inserting the template in the first line, because thats were the cursor starts, you want to append it? Good idea.

**Comment by SebastianBehrens** [comment]
@Vinzent03 Thank you for creating this.

Is this how one would then go about using this?
```
	ObjC.import("stdlib");
	ObjC.import("Foundation");
	const app = Application.currentApplication();
	app.includeStandardAdditions = true;
	// ...code 
	const templatePath = "default-template.md";
	// template in /vault-root/bin/templates/default-template.md
	const encodedTemplatePath = encodeURIComponent(templatePath);
	const templateCommandId = `obsidian-hotkeys-for-templates:${templatePath}`;
	
	const insertTemplateUri = `obsidian://advanced-uri?vault=${vaultNameEnc}&filepath=${filePathEnc}&commandid=${encodeURIComponent(templateCommandId)}`;
	app.openLocation(insertTemplateUri);
```
I want to insert the template in a file just like @Shuusei04.
