### ISSUE TITLE
[Bug] Advanced URI Stops Working With Obsidian 1.0.0

### ISSUE THREAD

**Issue by julroger2013** [Vinzent03/obsidian-advanced-uri#83]
The good news: Obsidian Released 1.0.0 publicly today!

The bad news: Something about the release seems incompatible with Advanced URI :(

On the latest pre-1.0.0 Insider Build (v0.16.5), Advanced URI links were working fine on both my Windows & Mac machines. 

Immediately after updating to v1.0.0, all of my previously functioning Advanced URI links return a "Vault Not Found" error. And this seems not to be a problem unique to my vault—the Sandbox Vault did the same thing.

**Comment by Vinzent03** [comment]
May you share your not working uri?

**Comment by julroger2013** [comment]
Sure, here's a representative URI - obsidian://advanced-uri?vault=The%2520Posnerium%25202.0&uid=2db965cf-6e1b-4dae-a75e-228b001065b0

I tried it on two different personal vaults as well as the sandbox vault, and with/without the use of UIDs. None of them worked for me, unfortunately. I'm sure it's just some goofy thing that has happened in updating my Obsidian installation. 

Thank you for making this amazingly helpful plugin!

**Comment by Vinzent03** [comment]
I don't think the issue lies in the Obsidian update. Did you create that uri in the last 3 days? I changed the encoding of the vault parameter in the last version.

**Comment by julroger2013** [comment]
I did create it just yesterday, yes. Unfortunately I don't have any older URIs to compare it to. 

But I thought I remembered creating a URI yesterday on my not-yet-updated MacOS Obsidian installation, which worked, only to have it fail once I updated Obsidian. Perhaps I'm misremembering, though.
