### ISSUE TITLE
`mode=open` for Writing Action

### ISSUE THREAD

**Issue by jandamm** [Vinzent03/obsidian-advanced-uri#88]
I would like to have a `mode=open` for the [write action](https://vinzent03.github.io/obsidian-advanced-uri/actions/writing).

I have written a little script to create a note for a given calendar entry.
In the end it calls `obsidian://advanced-uri?vault={Vault}&filepath={Filename}&data={Encoded Content}&mode=write`.

This works all fine unless the file already exists. I don't want to create a new file (`mode=new`) but instead just open the existing file. `write` does just show a notification that the file already exists.

Would be really nice if this could be added 🙂

**Comment by Vinzent03** [comment]
What about always opening the existing file instead of adding a new parameter?

**Comment by jandamm** [comment]
I'm not sure this helps.

A) File does not exist -> create new file with name and content

B) File does exist -> don't create a new file AND open the file

Currently I use the default mode which (`write`) where A works but doesn't open the file in case B.

**Comment by jandamm** [comment]
Thank you.
Now it works as expected 👍
