### ISSUE TITLE
[FR] Add a command to copy uri for current block. 

### ISSUE THREAD

**Issue by XMB-7** [Vinzent03/obsidian-advanced-uri#89]
Automatically generate a random block reference id for the active block, then copy the uri consisting of it to the clipboard. I think that would be awesome, making navigation to a specific location of a file handier.
Also thanks for developing this plugin, it really enhances my workflow.

**Comment by Vinzent03** [comment]
That should already be the case by using the `copy URI for current file` or `copy URI for file with options` commands.

**Comment by XMB-7** [comment]
According to the documentation, navigation to a block reference is feasible. But it seems no corresponding command there.
![image](https://user-images.githubusercontent.com/65625632/200604077-8eef871a-c1c6-4d3d-881e-feb88897eaf9.png)
![image](https://user-images.githubusercontent.com/65625632/200604460-4368f1f5-24bd-4c9a-adec-173c41455ed1.png)

Furthermore, currently we have first to assign a block with a reference id, then write a URI link to it, I'd hope with a provided command automating the two steps. Thanks.

**Comment by Vinzent03** [comment]
You have to place your cursor in the block and call one of the previous listed commands.

**Comment by XMB-7** [comment]
That only works when a block is assigned a reference id already.
![image](https://user-images.githubusercontent.com/65625632/200720685-33801868-e9e2-4175-93d3-50137a7f697d.png)

And what I expect is the following.
![image](https://user-images.githubusercontent.com/65625632/200721307-ff730ab3-2a3b-4bcd-92b6-ada178162a58.png)
 
Currently, we could first use other plugins like Copy Block Link or Carry-Forward to generate random block references, then execute the command available in Advanced-URI. I think it would be awesome if such block reference automating features can be absorbed, but it is definitely not a priority.

**Comment by Vinzent03** [comment]
I've added a new command, which generates the block reference for you.

**Comment by XMB-7** [comment]
Thank you so much. But the block reference seems to be assigned always to the last block instead of the expected one where the cursor locates.
![image](https://user-images.githubusercontent.com/65625632/203988998-9c3b911a-df37-4371-835b-cf0e39d5537c.png)

**Comment by Vinzent03** [comment]
Thanks. Will fix that.

**Comment by XMB-7** [comment]
Also appreciate that if the current block already has a reference, just take it instead of creating a new one. 
![image](https://user-images.githubusercontent.com/65625632/203998089-51b3bfe8-a57e-478d-b522-b5107aceb40b.png)

**Comment by Vinzent03** [comment]
Should be fixed now
