### ISSUE TITLE
[Feature Request] URI for Search Current File Command

### ISSUE THREAD

**Issue by FelipeRearden** [Vinzent03/obsidian-advanced-uri#90]
Hello @Vinzent03 !!!!!

MY FR is simple to explain: would be amazing if we could have  an URI for the Obsidian Command `Search current File`

`obsidian://advanced-uri?vault=<your-vault>&searchinfilequery=hello`

I know that sounds a crazy FR, but let me explain why ....

## My Workflow 

I realize that when I am searching for content inside the active note using the command `Search current File` 99% of the time I am searching for a term that is `selected` in the note or using the `clipboard`

This way, every time I have to <kbd>Mod+C</kbd> to copy the selection to the clipboard and hit  <kbd>Mod+V</kbd> to paste in the Search text field 

![55A9B3BC-5B76-427C-873E-E266CAA8721E](https://user-images.githubusercontent.com/85180696/202509089-ea9c1504-2925-49f5-8da0-5cfc94280ce4.jpeg)

## My Idea

My  idea is torun this URI from a Templater script.

 Using Templater, I could get the selection or clipboard using the command `tp.system.clipboard` or `tp.file.selection` and use `window.open()` to run the URI 

I already use this approach to perform a search in the whole vault using the standard `obsidian://search?vault=my%20vault&query=hello` URI

---

Thank you very much for reading this !!!!

Have a great day !!!!

**Comment by Vinzent03** [comment]
Hey! Am I missing something or can you simply preselect the text and call the command? Obsidian automatically searches for the selected text.
Clipboard would still be a valid use case.

**Comment by FelipeRearden** [comment]
> Hey! Am I missing something or can you simply preselect the text and call the command? Obsidian automatically searches for the selected text.

Hey @Vinzent03 !!! The problem is that Obsidian doesn't have URI for **Search in Current File** we only have a URI for Search for All Files in the Vault :)

In other words, we can select text and perform a search for all notes on the vault. My FR is about perform a search inside the Active Note :)

**Comment by Vinzent03** [comment]
You can use the `search` parameter now.

**Comment by FelipeRearden** [comment]
Amazing ! Working perfect on version `1.31.0` on Obsidian version `1.0.3`

Thank you very much @Vinzent03 !!!!!!!!! 💙
