### ISSUE TITLE
FilePath + Line navigation does not work when Obsidian is in Reading viewmode

### ISSUE THREAD

**Issue by gerryhernandez** [Vinzent03/obsidian-advanced-uri#91]
Great plugin! I'm working on integrating this with [Obsidian.nvim](https://github.com/epwalsh/obsidian.nvim) and have run into a snag.

This URI works perfectly when Obsidian is already in the Editing viewmode:
```
obsidian://advanced-uri?vault=main&filepath=test_note.md&line=42
```
However, if Obsidian is already in the Reading viewmode, the file does open successfully, but it doesn't scroll to the correct position in the file. It just stays wherever it is, or otherwise stays at the top if the file wasn't open to begin with.

Thanks for putting this plugin together!

**Comment by Vinzent03** [comment]
I'm switching to source mode now correctly.

**Comment by gerryhernandez** [comment]
Thanks for the speedy response, wow!

This is a pretty decent workaround. But is there any chance we could make it work while remaining in the Reading/viewing mode? The issue with the change is that it won't respect a user's current view state. It does scroll as expected, though, so that's good.

**Comment by Vinzent03** [comment]
I see, but I don't know if that's possible.

**Comment by gerryhernandez** [comment]
OK, no worries. This is good enough!

**Comment by pidgeon777** [comment]
Hello everyone, any update about this issue?

I see it is possible to specify view mode with URI, see:

https://vinzent03.github.io/obsidian-advanced-uri/concepts/navigation_parameters

But how can we exactly specify the view mode in the `obsidian://advanced-uri?vault=%s&filepath=%s&line=%i` URL, also?

**Comment by pidgeon777** [comment]
Would it be possible to add a setting to specify the default **view mode** and **open mode** to the already existing settings?

![image](https://user-images.githubusercontent.com/13739892/223446239-f195b212-04e4-4851-a243-94988a3179b0.png)

**Comment by Vinzent03** [comment]
@pidgeon777 You should be able to specify the line for `live` and `source` view mode.

**Comment by Vinzent03** [comment]
`viewmode` is just a parameter like `filepath`. An example is `obsidian://advanced-uri?vault=%s&filepath=%s&line=10&viewmode=live`. You can use the `preview` mode, but it currently doesn't work with the parameter `line`.

Switching temporarily to another mode is actually a good idea.

**Comment by pidgeon777** [comment]
> Switching temporarily to another mode is actually a good idea.

Eventually, this switch could be enabled in the Obsidian plugin panel with a new option, if users want to preserve the old behaviour until the `preview` mode will finally work with the `line` parameter.

I could beta-test your implementation once if done if you wish.

**Comment by pidgeon777** [comment]
> `viewmode` is just a parameter like `filepath`. An example is `obsidian://advanced-uri?vault=%s&filepath=%s&line=10&viewmode=live`. You can use the `preview` mode, but it currently doesn't work with the parameter `line`.
> 
> Switching temporarily to another mode is actually a good idea.

Hello @Vinzent03, any update?

**Comment by Vinzent03** [comment]
Thanks for the reminder, available in new release!

**Comment by pidgeon777** [comment]
I tested but unfortunately doesn't seem to work, my test:

1. Open the `Notes.md` file.

2. Move to line `x` in preview mode.

3. Execute:

`obsidian://advanced-uri?vault=VaultNAme&filepath=c%3A%5CPath%5CNotes.md&line=117&viewmode=preview`

As a result, `Obsidian` switches very quickly to line `117` (allegedly in edit mode), and then it goes back to line `x` in preview mode.

**Comment by pidgeon777** [comment]
Now, don't know what happened I think after the plugin update, it also reports:

![image](https://user-images.githubusercontent.com/13739892/229456207-b610be9f-4bc4-43af-870e-579ca29492fd.png)

When executing:

`obsidian://advanced-uri?vault=VaultName&filepath=c%3A%5CPath%5CNotes.md&line=117`

no matter if `viewmode` is specified or not.

**Comment by Vinzent03** [comment]
After doing some more test, I notice it's not always working. Sometimes it does, sometimes not. I found no way to solve this, so I'm for now not supporting it.

**Comment by pidgeon777** [comment]
Hello, I would like to ask if this problem still persists, or it has been fixed

Greetings
