### ISSUE TITLE
Add "Copy URI for Current Heading" Command

### ISSUE THREAD

**Issue by joelberger76** [Vinzent03/obsidian-advanced-uri#96]
Commands exist for copying URIs for the current file and current block. It would be nice to have the same for the current heading.

**Comment by Vinzent03** [comment]
It does that automatically, when you place the cursor in the heading line.

**Comment by XMB-7** [comment]
Could you please consider changing the command name from 'copy uri for current file' to 'copy uri for current file even heading' or something else to make this feature more apparent to users? Thanks.

**Comment by Vinzent03** [comment]
You are right that this feature is a bit hidden. It's documented [here](https://publish.obsidian.md/advanced-uri-doc/Tips/Helper+Commands), but I prefer to keep the commands shorter. I might highlight it more in the documentation or readme.
