### ISSUE TITLE
Copy adv. URI from current file (excalidraw), without switching to markdown mode 

### ISSUE THREAD

**Issue by anatoliibakhtin** [Vinzent03/obsidian-advanced-uri#97]
Hi ! I'm so glad I found this plugin ! Forgiving the headache and fear of losing the link ^_^
First of all I want to say - it is not so important, but it would be cool to have this feature:

When I use adv URI then to copy the link to the excalidraw picture I need to switch it to md mode so it will copy.  

https://user-images.githubusercontent.com/71871141/207044573-bd05a208-6aa1-4dcc-9a6c-ec46e98515a9.mp4

video steps:
1 open the same file on the left excalidraw mode on the right markdown mode
2 I try to copy adv URI from current file (Ctrl + L) nothing works
3 switch to markdown (Ctrl + Shift + E ) mode works

It would be more convenient, if I could copy adv URI directly, without switching modes, but if you think it is a trifle, I am more than happy with what I have :)

Thanks for your attention !

**Comment by anatoliibakhtin** [comment]
I get it, you're not interested))

**Comment by Vinzent03** [comment]
No, it should be fixed now! Could have wrote a message ...

**Comment by anatoliibakhtin** [comment]
Yes, it works, SUPER COOL! thank you !!
